<?php
ob_start();


include "connection1.php";

//this is for svn test
$xyz123=0;
  $id_url=$_REQUEST['id'];

  use PHPMailer\PHPMailer\PHPMailer;
  use PHPMailer\PHPMailer\Exception;
  if(isset($_REQUEST['link1']))
  {
  	/* Exception class. */
  	require 'C:\PHPMailer\src\Exception.php';

  	/* The main PHPMailer class. */
  	require 'C:\PHPMailer\src\PHPMailer.php';

  	/* SMTP class, needed if you want to use SMTP. */
  	require 'C:\PHPMailer\src\SMTP.php';

  	$mail = new PHPMailer(true);
  	$mail->isSMTP();
  	$mail->Host = 'smtp.gmail.com';
  	$mail->SMTPAuth = true;
  	//$mail->Username = 'sidambara.selvan@adrgrp.com'; //paste one generated by Mailtrap
  	//$mail->Password = 'Selvan1#$'; //paste one generated by Mailtrap
  	$mail->Username = 'test.deve@adrgrp.com';
  	$mail->Password = 'adrgrp@123';
  	$mail->SMTPSecure = 'tls';
  	$mail->Port = 587;
  	//$mail->Port = 465;
  	//From email address and name
  	$mail->From = "test.deve@adrgrp.com";
  	$mail->FromName = "Fotopia";

  	//To address and name
  	// $mail->addAddress("ssselvan.83@gmail.com", "Selvan");
  	// //$mail->addAddress("lakshminarayanan@adrgrp.com","Lakshmi"); //Recipient name is optional
  	// //$mail->addAddress("srivatsan@adrgrp.com","Srivatsan");
  	// $mail->addAddress("bharathwaj.v@adrgrp.com","Bharath");
  	 $mail->addAddress($_REQUEST['email']);


  	//Address to which recipient will reply
  	$mail->addReplyTo("test.deve@adrgrp.com", "Reply");

  	//CC and BCC
  	//$mail->addCC("cc@example.com");
  	//$mail->addBCC("bcc@example.com");

  	//Send HTML or Plain Text email
  	$mail->isHTML(true);

  	$mail->Subject = "Images shared with you through Fotopia";
  	$mail->Body = "<html><head><style>.titleCss {font-family: \"Roboto\",Helvetica,Arial,sans-serif;font-weight:600;font-size:18px;color:#0275D8 }.emailCss { width:100%;border:solid 1px #DDD;font-family: \"Roboto\",Helvetica,Arial,sans-serif; } </style></head><table cellpadding=\"5\" class=\"emailCss\"><tr><td align=\"left\"><img src=\"http://fotopia.adrgrp.com/logo.png\" /></td><td align=\"center\" class=\"titleCss\">Share Images</td><td align=\"right\">info@fotopia.com<br>343 4543 213</td></tr><tr><td colspan=\"2\"><br><br>";
  	//$mail->AltBody = "This is the plain text version of the email content";
  	$mail->Body.="Hello {{Editor_email}},<br>

   Photo share from {{you}} through Fotopia <br>
  <a href='{{link}}'
  target='_blank'>Click here</a> to view the shared images.<br><br>

  <br><br>
  Thanks,<br>
  Fotopia Team.
  ";
    // $mail->Body=str_replace('{{secret_code}}', $v , $mail->Body);
    $link=explode('?',$_REQUEST['link1']);
    $link1=$_SESSION['project_url']."sharelink.php?".$link[1];
  	$mail->Body=str_replace('{{link}}', $link1 , $mail->Body);
    // $mail->Body=str_replace('{{Photographer_Name}}', $x , $mail->Body);
  	// $mail->Body=str_replace('F{{orderId}}',$z, $mail->Body);
    	$mail->Body=str_replace('{{Editor_email}}',$_REQUEST['email'], $mail->Body);
      $mail->Body=str_replace('{{you}}',$_REQUEST['sharename'], $mail->Body);
  	$mail->Body.="<br><br></td></tr></table></html>";
  	// echo $mail->Body;exit;
    // exit;
  	try {
  	    $mail->send();
  	    //echo "Message has been sent successfully";
  	} catch (Exception $e) {
  		echo $e->getMessage();
  	    echo "Mailer Error: " . $mail->ErrorInfo;
  	}
  }

  if(isset($_REQUEST['reason']))
  {
    $id_url=$_REQUEST['id'];
    $order_staus_id=$_REQUEST['status_id'];
    $reason=$_REQUEST['reason'];

  mysqli_query($con,"UPDATE `orders` SET status_id='$order_staus_id',comment='$reason' WHERE id='$id_url'");

  $get_photographer = mysqli_query($con,"select * from orders where id='$id_url'");

  $get_photographer1 = mysqli_fetch_array($get_photographer);

  $realtor = $get_photographer1['created_by_id'];

  $photographer_id = $get_photographer1['photographer_id'];

  $get_pc_admin_csr =  mysqli_query($con,"select * from user_login where id='$photographer_id'");

  $get_pc_admin_csr1 = mysqli_fetch_array($get_pc_admin_csr);

  $pc_admin_id = $get_pc_admin_csr1['pc_admin_id'] ;

  $csr_id = $get_pc_admin_csr1['csr_id'] ;

$loggedin_name=$_SESSION['loggedin_name'];

  if($order_staus_id == 5)
  {

    $insert_action=mysqli_query($con,"INSERT INTO `user_actions`( `module`, `action`, `action_done_by_name`, `action_done_by_id`,`photographer_id`, `Realtor_id`,`pc_admin_id`,`csr_id`,`action_date`) VALUES ('Canceled','order','$loggedin_name',$realtor,$photographer_id,$realtor,$pc_admin_id,$csr_id,now())");

  }
  }

  if(isset($_REQUEST['chattext']))
{

$created_by_id=$_REQUEST['created_by_id'];
$from_user_id=$_SESSION["loggedin_id"];
$chat_message=$_REQUEST['chattext'];
$order_id=$_REQUEST['order_id'];
//echo "insert into chat_message(to_user_id,from_user_id,chat_message,timestamp,order_id)values('$created_by_id','$from_user_id','$chat_message',now(),'$order_id'";exit;
mysqli_query($con,"insert into chat_message(to_user_id,from_user_id,chat_message,timestamp,order_id)values('$created_by_id','$from_user_id','$chat_message',now(),'$order_id')");
}
  if(isset($_POST['ZIP']))
  {
  //  mkdir('./temp');


      $image=@$_REQUEST['selected_image'];

    $data1=explode('/',$_POST['folderToZip']);

    foreach($image as $id)
    {

    $get_image_query=mysqli_query($con,"select * from img_upload where id=$id");
    $get_image=mysqli_fetch_array($get_image_query);

    $file1=$_POST['folderToZip']."/".$get_image['img'];

      $file="./temp/".$get_image['img'];
    copy($file1,$file);
    }

    $dir = "./temp";
    $zip_file = "Fotopia".time().".zip";
  // Get real path for our folder
  $rootPath = realpath($dir);

  // Initialize archive object
  $zip = new ZipArchive();
  $zip->open($zip_file, ZipArchive::CREATE | ZipArchive::OVERWRITE);

  // Create recursive directory iterator
  /** @var SplFileInfo[] $files */
  $files = new RecursiveIteratorIterator(
      new RecursiveDirectoryIterator($rootPath),
      RecursiveIteratorIterator::LEAVES_ONLY
  );

  foreach ($files as $name => $file)
  {
      // Skip directories (they would be added automatically)
      if (!$file->isDir())
      {
          // Get real and relative path for current file
          $filePath = $file->getRealPath();
          $relativePath = substr($filePath, strlen($rootPath) + 1);
          // Add current file to archive
          $zip->addFile($filePath, $relativePath);
      }
  }

  // Zip archive will be created only after closing object
  $zip->close();


  header('Content-Description: File Transfer');
  header('Content-Type: application/octet-stream');
  header('Content-Disposition: attachment; filename='.basename($zip_file));
  header('Content-Transfer-Encoding: binary');
  header('Expires: 0');
  header('Cache-Control: must-revalidate');
  header('Pragma: public');
  header('Content-Length: ' . filesize($zip_file));
  readfile($zip_file);
  unlink($zip_file);
  }
 delete_files('./temp');
  function delete_files($dir) {
    // echo '<script>alert("yes");</script>';
  foreach(glob($dir . '/*') as $file) {
    if(is_dir($file)) delete_files($file); else unlink($file);

  } ;


}


?>
<?php
if(isset($_REQUEST['rework']))
{
  $image=$_REQUEST['selected_image'];
  $id_url=$_REQUEST['id'];

  foreach($image as $id)
  {

  $get_image_query=mysqli_query($con,"select * from img_upload where id=$id");
  $get_image=mysqli_fetch_array($get_image_query);
  //echo $_POST['folderToZip'];
    $data1=explode('/',$_POST['folderToZip']);
  $file1=$_POST['folderToZip']."/".$get_image['img'];
  if($data=@mkdir("rework_images/order_".$id_url))
  {

  }
  if($data=@mkdir("rework_images/order_".$id_url."/".$data1[2]))
  {

  }
  // mkdir("rework_images/order_".$id_url);
  // mkdir("rework_images/order_".$id_url."/".$data1[3]);
    $file="rework_images/order_".$id_url."/".$data1[2]."/".$get_image['img'];
  rename($file1,$file);
  }

  $comment=@$_REQUEST['comment'];
  $service_ID=@$_REQUEST['service_ID'];
  mysqli_query($con,"UPDATE `raw_images` SET `comments` = '$comment' WHERE order_id='$id_url' and service_name='$service_ID'");
  mysqli_query($con,"update orders SET status_id=4 where id=$id_url");
$get_photographer = mysqli_query($con,"select * from orders where id='$id_url'");

$get_photographer1 = mysqli_fetch_array($get_photographer);

$photographer_id = $get_photographer1['photographer_id'];

$loggedin_id=$_SESSION['loggedin_id'];
$loggedin_name=$_SESSION['loggedin_name'];

$get_pc_admin_csr =  mysqli_query($con,"select * from user_login where id='$photographer_id'");

$get_pc_admin_csr1 = mysqli_fetch_array($get_pc_admin_csr);

$pc_admin_id = $get_pc_admin_csr1['pc_admin_id'] ;

$csr_id = $get_pc_admin_csr1['csr_id'] ;

$insert_action=mysqli_query($con,"INSERT INTO `user_actions`( `module`, `action`, `action_done_by_name`, `action_done_by_id`,`photographer_id`, `Realtor_id`,`pc_admin_id`,`csr_id`,`action_date`) VALUES ('Rework','assigned','$loggedin_name',$loggedin_id,$photographer_id,$loggedin_id,$pc_admin_id,$csr_id,now())");

}

?>

<?php include "header.php";  ?>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.5.0/jszip.min.js" integrity="sha512-y3o0Z5TJF1UsKjs/jS2CDkeHN538bWsftxO9nctODL5W40nyXIbs0Pgyu7//icrQY9m6475gLaVr39i/uh/nLA==" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/2.0.0/FileSaver.js" integrity="sha512-UNbeFrHORGTzMn3HTt00fvdojBYHLPxJbLChmtoyDwB6P9hX5mah3kMKm0HHNx/EvSPJt14b+SlD8xhuZ4w9Lg==" crossorigin="anonymous"></script>
<style>
.scrollbar
{
	margin-left: -10px;
	float: left;
  height: 385px;
  width: 191px;
	background: #F5F5F5;
	overflow-y: scroll;
	margin-bottom: 25px;
}
.padding
{
	padding-right: 334px;
}
#wrapper
{
	text-align: center;
	width: 500px;
	margin: auto;
}
/*
 *  STYLE 1

 */
 @media print {
/* style sheet for print goes here */
.noprint {
visibility: hidden;
}
}

#style-1::-webkit-scrollbar-track
{
	-webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3);
	border-radius: 10px;
	background-color: #F5F5F5;
}

#style-1::-webkit-scrollbar
{
	width: 80px;
	background-color: #F5F5F5;
}

#style-1::-webkit-scrollbar-thumb
{
	border-radius: 10px;
	-webkit-box-shadow: inset 0 0 6px rgba(0,0,0,.3);
	background-color: #555;
}
.modal {
  display: none;
  overflow: hidden;
  position: fixed;
  top: 178px;
  right: 680px;
  bottom: 0;
  left: 300px;
  z-index: 1050;
  -webkit-overflow-scrolling: touch;
  outline: 0;
}
th{
  width:150px;
}
.img-box:hover{
  background-color: none;
}
/* .gallery .img-box, .gallery .img-box img
{
  max-width: 50px !important;
} */
#imga
{
  display: inline;
  width: 100% !important;
  max-width: 50px !important;
  top: 43px;
  background:#000;
  color:#FFF;
  border-radius:0px 20px 20px 0px;
  padding: 11px 0px;
  z-index: 1;
}
#imga1
{
  float: right;
  width: 100% !important;
  max-width: 50px !important;
  top: 50px;
   background:#000;
  color:#FFF;
  border-radius:20px 0px 0px 20px;
  display: inline-block;
  overflow: hidden;
  max-width: 100%;
  outline: none !important;
  position: relative;
  text-align: left;
  /* font-size: 18px; */
      padding: 8px 3px 8px 15px;
  z-index: 1;

}
.img-box:before{
  background: none !important;
}

td{
padding-right:15px;
}

.nav-tabs > li.active > a, .current-active {
    background:#000!important;color:#FFF!important;
    border-radius: 20px 20px 0px 0px;
    opacity: 0.8;


}
.current-active
{
 background:#000!important;
 color:#FFF!important;border-bottom-color:#000!important;
}
.btn-default
{
padding-top:5px!important;
border-radius:20px;
}


.mfp-container.mfp-s-ready.mfp-image-holder.active
{
background:none!important;
}
.mfp-counter
{
right:auto;
float:left!important;
}
.mfp-title
{
text-align:center;
}
.nonviewed{
  opacity:0.3;
}



html{	background-color:#FFF; }

/* The ribbon */

.ribbon {
    width: 100px;
    height: 50px;
    background-color: #000;
    position: absolute;
    right: 0px;
    top: -350px;
	border-radius:25px 0px 0px 25px;
    -webkit-animation: drop forwards 0.8s 1s cubic-bezier(0.165, 0.84, 0.44, 1);
    animation: drop forwards 0.8s 1s cubic-bezier(0.165, 0.84, 0.44, 1);
}




@keyframes drop{
	0%		{ top:-350px; }
	100%	{ top:0; }
}



@-webkit-keyframes swinging{
    0%{-webkit-transform: rotate(10deg);}
    50%{-webkit-transform: rotate(-5deg)}
    100%{-webkit-transform: rotate(10deg);}
}

@keyframes swinging{
    0%{transform: rotate(10deg);}
    50%{transform: rotate(-5deg)}
    100%{transform: rotate(10deg);}
}

.swingimage{
    -webkit-transform-origin: 50% 0;
    transform-origin: 50% 0;
    -webkit-animation: swinging 3.5s ease-in-out forwards infinite;
    animation: swinging 3.5s ease-in-out forwards infinite;
	background-image:url(price1.png);
	background-repeat: no-repeat;
  background-size:60px 80px;
}
.mfp-container 
{
background:none!important;
}
</style>
<script>
function chechcond()
{
  aler("check");
    if($('.selectimg').prop("checked",true)==true)
    {
      return true;
    }
    else {
     
	  var langIs='<?php echo $_SESSION['Selected_Language_Session']; ?>';
		var alertmsg='';
		if(langIs=='no')
		{
		alertmsg="Velg et bilde";
		}
		else
		{
		alertmsg="Select one image";
		}
alert(alertmsg);
      return false;
    }
}
function downloadbtn()
{
   $("#comment2").removeAttr('required');


}
function shareme(d)
{
   $("#link").val(d);
   // document.execCommand("copy");
   //
   // /* Alert the copied text */
   // alert("Copied the text: " + d);

}
function selectAllImages()
{




  if(document.getElementById('allimages').value == 0)
  {

  var a=document.getElementById('allimages').value=1;
    $(".img1").css('opacity','0.7');
    $('.icons').removeClass('fa fa-square');
    $('.icons').addClass('fa fa-check-square');
    $('.selectimg').prop("checked",true);
    var c=$('#counts').val();
     $('#count').val(c);
  }
  else {
    var a=document.getElementById('allimages').value=0;
      $(".img1").css('opacity','1');
      $('.icons').removeClass('fa fa-check-square');
      $('.icons').addClass('fa fa-square');
        $('.selectimg').prop("checked",false);
        $('#count').val('0');
  }



}

function clickimg(id)
{
  var c=$('#count').val();
 if($("#selected_image"+id).prop("checked") == false)
  {

    $("#selected_image"+id).prop("checked",true);
  $("#clicked_img"+id).css('opacity','0.4');
  $("#check"+id).removeClass('fa fa-square');
  $("#check"+id).addClass('fa fa-check-square');
  c++;
  //  c++;
  $('#count').val(c);
   if($('#counts').val()==c)
   {
       $("#remove").prop("checked",true);
   }
  }
  else {
      // var c=$('#counts').val();
    $("#check"+id).removeClass('fa fa-check-square');
      $("#check"+id).addClass('fa fa-square');
    $("#selected_image"+id).prop("checked",false);
    $("#clicked_img"+id).css('opacity','1');
       c--;
    $('#count').val(c);
    $("#remove").prop("checked",false);
  }

}
// / floor
function downloadbtn2()
{
   $("#comment22").removeAttr('required');
   $("#zipDownload2").submit();
}
function shareme2(d)
{
$("#link").val(d);
}
function selectAllImages2()
{
  if(document.getElementById('allimages2').value == 0)
  {

  var a=document.getElementById('allimages2').value=1;
    $(".img12").css('opacity','0.7');
    $('.icons2').removeClass('fa fa-square');
    $('.icons2').addClass('fa fa-check-square');
    $('.selectimg2').prop("checked",true);
    var c=$('#counts2').val();
     $('#count2').val(c);
  }
  else {
    var a=document.getElementById('allimages2').value=0;
      $(".img12").css('opacity','1');
      $('.icons2').removeClass('fa fa-check-square');
      $('.icons2').addClass('fa fa-square');
        $('.selectimg2').prop("checked",false);
         $('#count2').val('0');
  }
}
function clickimg2(id)
{
var c=$('#count2').val();
 if($("#selected_image2"+id).prop("checked") == false)
  {

    $("#selected_image2"+id).prop("checked",true);
  $("#clicked_img2"+id).css('opacity','0.7');
  $("#check2"+id).removeClass('fa fa-square');
  $("#check2"+id).addClass('fa fa-check-square');
  c++;
  $('#count2').val(c);
  if($('#counts2').val()==c)
  {
      $("#remove2").prop("checked",true);
  }
  }
  else {
    $("#check2"+id).removeClass('fa fa-check-square');
      $("#check2"+id).addClass('fa fa-square');
    $("#selected_image2"+id).prop("checked",false);
    $("#clicked_img2"+id).css('opacity','1');
    c--;
    $('#count2').val(c);
    $("#remove2").prop("checked",false);
  }

}
// Drone
function downloadbtn3()
{
   $("#comment23").removeAttr('required');
   $("#zipDownload3").submit();
}
function shareme3(d)
{
$("#link").val(d);

}
function selectAllImages3()
{
  if(document.getElementById('allimages3').value == 0)
  {

  var a=document.getElementById('allimages3').value=1;
    $(".img13").css('opacity','0.7');
    $('.icons3').removeClass('fa fa-square');
    $('.icons3').addClass('fa fa-check-square');
      $('.selectimg3').prop("checked",true);
      var c=$('#counts3').val();
       $('#count3').val(c);
  }
  else {
    var a=document.getElementById('allimages').value=0;
      $(".img13").css('opacity','1');
      $('.icons3').removeClass('fa fa-check-square');
      $('.icons3').addClass('fa fa-square');
        $('.selectimg3').prop("checked",false);
          $('#count3').val('0');
  }



}
function clickimg3(id)
{
var c=$('#count3').val();
 if($("#selected_image3"+id).prop("checked") == false)
  {

    $("#selected_image3"+id).prop("checked",true);
  $("#clicked_img3"+id).css('opacity','0.7');
  $("#check3"+id).removeClass('fa fa-square');
  $("#check3"+id).addClass('fa fa-check-square');
  c++;
  $('#count3').val(c);
  if($('#counts3').val()==c)
  {
      $("#remove3").prop("checked",true);
  }
  }
  else {
    $("#check3"+id).removeClass('fa fa-check-square');
      $("#check3"+id).addClass('fa fa-square');
    $("#selected_image3"+id).prop("checked",false);
    $("#clicked_img3"+id).css('opacity','1');
    c--;
    $('#count3').val(c);
    $("#remove3").prop("checked",false);
  }

}
// hdr_photos
function downloadbtn4()
{
   $("#comment24").removeAttr('required');
   $("#zipDownload4").submit();
}
function shareme4(d)
{


$("#link").val(d);

}
function selectAllImages4()
{
  if(document.getElementById('allimages4').value == 0)
  {

  var a=document.getElementById('allimages4').value=1;
    $(".img14").css('opacity','0.7');
    $('.icons4').removeClass('fa fa-square');
    $('.icons4').addClass('fa fa-check-square');
      $('.selectimg4').prop("checked",true);
      var c=$('#counts4').val();
       $('#count4').val(c);

  }
  else {
    var a=document.getElementById('allimages4').value=0;
      $(".img14").css('opacity','1');
      $('.icons4').removeClass('fa fa-check-square');
      $('.icons4').addClass('fa fa-square');
        $('.selectimg4').prop("checked",false);
            $('#count4').val('0');
  }



}
function clickimg4(id)
{
var c=$('#count').val();
 if($("#selected_image4"+id).prop("checked") == false)
  {

    $("#selected_image4"+id).prop("checked",true);
  $("#clicked_img4"+id).css('opacity','0.7');
  $("#check4"+id).removeClass('fa fa-square');
  $("#check4"+id).addClass('fa fa-check-square');
  c++;
  $('#count4').val(c);
  if($('#counts4').val()==c)
  {
      $("#remove4").prop("checked",true);
  }
  }
  else {
    $("#check4"+id).removeClass('fa fa-check-square');
      $("#check4"+id).addClass('fa fa-square');
    $("#selected_image4"+id).prop("checked",false);
    $("#clicked_img4"+id).css('opacity','1');
    c--;
    $('#count4').val(c);
    $("#remove4").prop("checked",false);
  }

}

 function done(order_id)
  {
   if(confirm("Are you sure want to complete the order?"))
   {
   var xhttp = new XMLHttpRequest();
   xhttp.onreadystatechange = function() {
   if (this.readyState == 4 && this.status == 200)
   {
   //  document.getElementById("drone_msg").innerHTML = this.responseText;
   }
   };
    xhttp.open("GET","done.php?id="+order_id, true);
    xhttp.send();
    // window.location.href = "order_list.php";
    window.location.href = "rating.php?order_id="+order_id;
   }
   }
   function status_change(d)
   {
     if(d==5)
     {
         $("#title").html('Cancel the order');
         // $("#error").html('Reason for Decline:');
         $("#status_id").val(d);
      $("#send").click();

     }

   }
   function viewed(data)
   {
     var a=data;

     var xhttp = new XMLHttpRequest();
   xhttp.onreadystatechange = function() {
    if (this.readyState == 4 && this.status == 200) {
      $("#clicked_img"+a).removeClass("nonviewed");
      $("#clicked_img1"+a).removeClass("nonviewed");
      $("#clicked_img2"+a).removeClass("nonviewed");
      $("#clicked_img3"+a).removeClass("nonviewed");
    }
   };
   xhttp.open("GET","./viewed.php?id="+a, true);
   xhttp.send();

   }

function Getcomment(data)
{
  var a=data;
  var c=$("#s"+data).val();

  var xhttp = new XMLHttpRequest();
xhttp.onreadystatechange = function() {
 if (this.readyState == 4 && this.status == 200) {
 doucument.getElementById("s"+c).value=a;
 }
};
xhttp.open("GET","comment.php?id="+a+"&data="+c, true);
xhttp.send();
alert("comment changed");
}
</script>
<?php if(@isset($_REQUEST["c"])) { ?>
 <script>$(document).ready(function() {
 $("#click1").removeClass("active");
 $("#click5").addClass("active");
 $("#tab5").addClass("active");
 $("#tab1").removeClass("active");
});



  </script>
  <?php } ?>

 <div class="section-empty bgimage3">
        <div class="container" style="margin-left:0px;height:inherit;">
            <div class="row">
			<hr class="space s">
                <div class="col-md-2" style="margin-left:-15px;">

	   <?php include "sidebar.php";  ?>

                </div>


                <div class="col-md-8" >

<div class="tab-box" data-tab-anima="show-scale">
<ul class="nav nav-tabs nav-justified">
<li id="click1" class="active"><a href="#" adr_trans="label_order_detail">Order Detail</a></li>
<!-- <li id="click2"><a href="#">Homeseller Info</a></li> -->
<li id="click3"><a href="#" adr_trans="label_finished_images">Finished Images </a></li>

<?php
$get_order_query1=mysqli_query($con,"SELECT * FROM orders where id='$id_url'");
$get_order1=mysqli_fetch_array($get_order_query1);
if($get_order1['status_id']==3||$get_order1['status_id']==1||$get_order1['status_id']==2||$get_order1['status_id']==4)
{
  $approved_check_query=mysqli_query($con,"SELECT * FROM `invoice` where order_id=".$id_url);
  @$approved_check=mysqli_fetch_assoc(@$approved_check_query);
     if(@$approved_check['approved']==1)
     {
       echo '<li id="click5" ><a  href="#tab5" data-toggle="tab" adr_trans="label_order_cost">Order Cost</a></li>';
     }
}
?>
<li id="click4"><a href="#tab4" adr_trans="label_add_on">Add ons </a></li>
</ul>
<div class="panel active" id="tab1">

  <!-- start order details-->

  <?php
              $order_id=$id_url;
              $get_summary_query=mysqli_query($con,"SELECT * from orders WHERE id='$order_id'");
              $get_summary=mysqli_fetch_array($get_summary_query);
  $hs_id=$get_summary['home_seller_id'];

   $homeSeller=mysqli_query($con,"SELECT * from home_seller_info WHERE id='$hs_id'");
              $homeSeller1=mysqli_fetch_array($homeSeller);

              $photographer_id=$get_summary['photographer_id'];
              $get_photgrapher_name_query=mysqli_query($con,"SELECT * FROM user_login where id='$photographer_id'");
              $get_name=mysqli_fetch_assoc($get_photgrapher_name_query);
              $photographer_Name=@$get_name["first_name"]."".@$get_name["last_name"];
              ?>
              <?php

               $total_cost=mysqli_query($con,"SELECT sum(total_price) as totalPrice from order_products WHERE order_id='$order_id'");
                  $total_cost1=mysqli_fetch_array($total_cost);



              ?>
 <div class="col-md-12"><div class="ribbon" style="padding-left:13px;font-weight:600;padding-top:5px;color:#FFF"><span adr_trans="label_order_value">Order Value</span><br /><span style="padding-left:20px;">$<?php echo $total_cost1['totalPrice']?></span></div></div>



  <div class="row" style="margin:20px;" id="printArea">

  				<div class="col-md-6">
				<!-- <table width="100%"><tr><td colspan="3" align="right" style="z-index:999;position:absolute;float:right;margin-left:220px;margin-top:-30px;width:100px;height:100px;border-radius:20px" class="swingimage"><br /><span style="margin-right:40px;font-weight:600;color:#FFF;">Value</span><br />
				<span style="margin-right:40px;font-weight:600;color:#FFF;">$600</span>
				 </td></tr></table> -->
  			           <p align="left" id="label_order_details" adr_trans="label_order_details" style="color:#000080;font-weight:600;font-size:15px;">Order Details</p>
  				<table class="" style="color:#000;font-weight:600;font-size:12px;">

  				<tr>
  			  <td id="label_order_no" adr_trans="label_order_no" style="width:150px;">Order #</td><td>:</td><td><?php echo $get_summary['id']; ?></td>
  				</tr>
          <tr>
          <td>Reference Number</td><td>:</td><td><?php echo $homeSeller1['reference_number']; ?></td>
          </tr>
  			                   	<tr>
  			                    <td id="label_property_type" adr_trans="label_property_type">Property Type</td><td>:</td><td><?php echo $get_summary['property_type']?></td>
                            </tr>
                            <tr>
                            <td id="label_property_address" adr_trans="label_property_address">Property Address</td><td>:</td><td><?php echo $get_summary['property_address']?></td>
                            </tr>
                            <tr>
                            <td id="label_floors" adr_trans="label_floors">No. Of Floors</td><td>:</td><td><?php echo $get_summary['number_of_floor_plans']?></td>
                            </tr>
                            <tr>
                            <td id="label_area" adr_trans="label_area">Area</td><td>:</td><td><?php echo $get_summary['area']?></td>
                            </tr>
                            <tr>

                            </tr>
                            <tr>
                            <td id="label_session_date_time" adr_trans="label_session_date_time">Session Date & Time</td><td>:</td><td><?php if($get_summary['session_from_datetime']!='0000-00-00 00:00:00') { echo date("d-m-Y H:i a",strtotime($get_summary['session_from_datetime']))." - ". date("d-m-Y H:i a",strtotime($get_summary['session_to_datetime'])); } else { echo "Session not booked yet.";  } ?></td>
                            </tr>
                            <tr>
                            <td id="label_realtor_name" adr_trans="label_realtor_name">Realtors Name</td><td>:</td><td>
                              <?php
                                $realtorID=$get_summary['created_by_id'];
                                $get_realtor_name_query=mysqli_query($con,"SELECT * FROM user_login where id='$realtorID'");
                                $get_realtor_name=mysqli_fetch_assoc($get_realtor_name_query);
                                echo $get_realtor_name1=$get_realtor_name["first_name"]."".$get_realtor_name["last_name"];
                                ?>
                            </td>
                            </tr>
                            <tr>
                            <td id="label_realtor_contact" adr_trans="label_realtor_contact">Realtors Contact</td><td>:</td><td><?php echo $get_realtor_name["contact_number"]; ?></td>
                            </tr>
                            <tr>
                            <td id="label_realtor_email" adr_trans="label_realtor_email">Realtors Email</td><td>:</td><td><?php echo $get_realtor_name["email"]; ?></td>
                            </tr>
                            <tr>
                            <td id="label_due_date" adr_trans="label_due_date">Due Date</td><td>:</td><td><?php echo $get_summary['order_due_date']; ?></td>
                            </tr>
                            <tr>
                            <td id="label_booking_notes" adr_trans="label_booking_notes">Booking Notes</td><td>:</td><td><?php echo $get_summary['booking_notes']; ?></td>
                            </tr>
                            <tr>
                            <td id="label_status" adr_trans="label_status">Status</td><td>:</td><td><?php $status=$get_summary['status_id']; if($status==1) { echo "<span id='label_created' adr_trans='label_created' style='color:green;font-weight:bold;'>Created</span>"; } elseif($status==2){echo "<span id='label_wip' adr_trans='label_wip' style='color:brown;font-weight:bold;'>WIP</span>";}elseif($status==3){echo "<span id='label_completed' adr_trans='label_completed' style='color:green;font-weight:bold;'>completed</span>";}elseif($status==4){echo "<span id='label_rework' adr_trans='label_rework' style='color:green;font-weight:bold;'>Rework</span>";}elseif($status==6){echo "<span id='label_declined' adr_trans='label_declined' style='color:Red;font-weight:bold;'>Declined</span>";}elseif($status==7){echo "<span id='label_working_customer' adr_trans='label_working_customer' style='color:orange;font-weight:bold;'>Working with Customer</span>";}elseif($status==5){echo "<span style='color:Red;font-weight:bold;'>Cancelled</span>";}?></td>  </tr>
                              <?php if($status==5||$status==6||$status==7){?>
                                <tr><td >Reason</td><td>:</td><td><?php echo $get_summary['comment']; ?></td></tr><?php } ?>

                            </table>
                            <?php
                           if($get_summary['status_id']==1)
                           {?>
                            <select class="form-control" name="status" id="status" onchange="status_change(this.value)" style="width:195px">
                              <option value="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;--Order Status-- </option>
                                <option value="5">Cancel the order</option>

                        </select>
<a href="#tnc1" class="btn btn-default lightbox link"  name="" id="send"  style="display:none"></a>
                        <?php
                         }
                        ?>
                            <br />
                            <p id="label_order_products" adr_trans="label_order_products" align="left" style="color:#000080;font-weight:600;font-size:15px;">Products For the Order</p>

  				<table style="color:#000;font-weight:600;font-size:12px;min-height:50px">
  				<?php

  				 $prodsList=mysqli_query($con,"SELECT * from products where id in(select product_id from order_products WHERE order_id='$order_id')");

$get_product =  mysqli_query($con,"SELECT * FROM order_products WHERE order_id ='$order_id'");

              while($product_title=mysqli_fetch_array($get_product))
  			{

  				?>
  				<tr>
  				<td><?php echo $product_title['product_title']; ?></td><td>X</td><td><?php echo $product_title['quantity']; ?></td>
  				</tr>
  				<?php } ?>

  				</table>
          
  				</div>
  				<div class="col-md-6">

  			                     <p align="left" id="label_homeseller_info" adr_trans="label_homeseller_info" style="color:#000080;font-weight:600;font-size:15px;">Home Seller Info</p>

                    <table class="" style="color:#000;font-weight:600;font-size:12px;">
                            <tr>
                            <td id="label_homeseller_name" adr_trans="label_homeseller_name">Home Seller Name</td><td>:</td><td><?php echo $homeSeller1['name']; ?></td>
                            </tr>
                            <tr>
                            <td id="label_homeseller_address" adr_trans="label_homeseller_address">Home Seller Address</td><td>:</td><td><?php echo $homeSeller1['address'].",".$homeSeller1['city'];?></td>
                            </tr>

                            <tr>
                            <td id="label_homeseller_contact" adr_trans="label_homeseller_contact">Home Seller Contact</td><td>:</td><td><?php echo $homeSeller1['mobile_number'];?></td>
                            </tr>

                            <tr>
                            <td id="label_homeseller_email" adr_trans="label_homeseller_email">Home Seller Email</td><td>:</td><td><?php echo $homeSeller1['email'];?></td>
                            </tr>

  				</table>
  				<br />
  				<div class="col-md-12" id="googleMap" style="width:100%;height:250px;"></div>

  <script>
  function myMap() {
  var mapProp= {
    center:new google.maps.LatLng(59.9139,10.7522),
    zoom:7,
  };
  var map = new google.maps.Map(document.getElementById("googleMap"),mapProp);
  }

  function check1(){
   // alert("yes");
      $("#comment2").attr("required",true);
  if($("#count").val()!=''&&($("#count").val()!=0))
   {
     $("#comment2").Attr("required");
     return true;

   }
   else{
	 var langIs='<?php echo $_SESSION['Selected_Language_Session']; ?>';
		var alertmsg='';
		if(langIs=='no')
		{
		alertmsg="Klikk på bilde for å laste ned eller gjør om";
		}
		else
		{
		alertmsg="click one image to download or rework";
		}
alert(alertmsg);
     return false;
   }
 }
 function check2(){
  $("#comment22").attr("required",true);
  if($("#count2").val()!=''&&($("#count2").val()!=0))
  {
       $("#comment2").Attr("required");
    return true;

  }
  else{
    var langIs='<?php echo $_SESSION['Selected_Language_Session']; ?>';
		var alertmsg='';
		if(langIs=='no')
		{
		alertmsg="Klikk på bilde for å laste ned eller gjør om";
		}
		else
		{
		alertmsg="click one image to download or rework";
		}
alert(alertmsg);
    return false;
  }
}
function check3(){
  $("#comment23").attr("required",true);
 if($("#count3").val()!=''&&($("#count3").val()!=0))
 {
   return true;
    $(".comment").Attr("required");
 }
 else{
   var langIs='<?php echo $_SESSION['Selected_Language_Session']; ?>';
		var alertmsg='';
		if(langIs=='no')
		{
		alertmsg="Klikk på bilde for å laste ned eller gjør om";
		}
		else
		{
		alertmsg="click one image to download or rework";
		}
alert(alertmsg);
   return false;
 }
}
function check4(){
  $("#comment24").attr("required",true);
 if($("#count4").val()!=''&&($("#count4").val()!=0))
 {
   return true;
    $(".comment").Attr("required");
 }
 else{
   var langIs='<?php echo $_SESSION['Selected_Language_Session']; ?>';
		var alertmsg='';
		if(langIs=='no')
		{
		alertmsg="Klikk på bilde for å laste ned eller gjør om";
		}
		else
		{
		alertmsg="click one image to download or rework";
		}
alert(alertmsg);
   return false;
 }
}

function showicons(iconid)
{
  //alert(iconid);
$('.icons'+iconid).css("visibility","visible");

}
function hideicons(iconid1)
{
    //alert(iconid1);
$('.icons'+iconid1).css("visibility","hidden");

}


  </script>

  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCpWF2v01q7IpMiUSICKhd9zndRFb_kxf8&callback=myMap"></script>



  				</div>

  </div>
  <!-- end order details-->

</div>

<div class="panel" id="tab3" style="border-radius:50px;">
            <input type="hidden" id="count"/>
            <input type="hidden" id="count2"/>
            <input type="hidden" id="count3"/>
            <input type="hidden" id="count4"/>
         <p align="right">
           <?php if($get_summary['status_id']==2){?>
              <input type="button" id="done_hide"  class="btn btn-default" style="" onclick="done(<?php echo $id_url; ?>)"  value="Mark as Complete"></p>
            <?php } ?>
            <?php if($get_summary['status_id']==3)
            {
               echo '<script>$("#done_hide").hide();</script>';
            }
             ?>
			 <br />
                      <div class="tab-box pills" data-tab-anima="fade-right">
                          <ul class="nav nav-pills nav-justified">
                              <li class="current-active active"><a href="#" adr_trans="label_standard_photos">Standard Photos</a></li>
                              <li class=""><a href="#" adr_trans="label_floor_plans1">Floor Plans</a></li>
                              <li class=""><a href="#" adr_trans="label_drone_photos">Drone Photos</a></li>
                                <li class=""><a href="#" adr_trans="label_hdr_photos">Hdr Photos</a></li>
                          </ul>
                          <div class="panel active fade-right" style="transition-duration: 300ms; animation-duration: 300ms; transition-timing-function: ease; transition-delay: 0ms;">
                            <div style="border-bottom: 1px solid black">

                                 <form onsubmit="return check1();" name="zipDownload" id="zipDownload" method="post"  >
                               <input type="checkbox" id="remove" onclick="selectAllImages()">&nbsp;<b adr_trans="label_select_all">Select All</b></input>
                               <button name="rework" onclick="reworks();" style="background-color: black;float:right;margin-right:20px;margin-top:-10px;border-radius: 12px;color: white;" adr_trans="label_rework">Rework</button>
                            </div>
                            <div class="maso-list gallery">
                              <div class="maso-box row no-margins" data-options="anima:fade-in" style="position: relative;">
                                 <input type="hidden" id="allimages" name="allimages" value="0">
                              <?php
                              $imagesDirectory_standard = "./finished_images/order_".$id_url."/standard_photos";
                              $i=0;
                              if (is_dir($imagesDirectory_standard))
                              {
                               $opendirectory = opendir($imagesDirectory_standard);


                              while (($image = readdir($opendirectory)) !== false)
                               {
                                 if(($image == '.') || ($image == '..'))
                                 {
                                   continue;
                                 }
                                 $i++;
                                 $imgFileType = pathinfo($image,PATHINFO_EXTENSION);

                                 if(($imgFileType == 'jpg') || ($imgFileType == 'png'))
                                 {

                                  ?>

                                  <?php
                                //  echo "select * from img_upload where order_id=$id_url and img='$image'";
                                  $get_comment_querry=mysqli_query($con,"select * from img_upload where order_id=$id_url and img='$image'");
                                  $get_comment=mysqli_fetch_assoc($get_comment_querry);


                                  $checknaming=mysqli_query($con,"select * from image_naming where order_id=$id_url and image_name='$image'");
                                  $checknaming1=mysqli_fetch_assoc($checknaming);
                                  if($checknaming1['description']=="")
                                  {
                                  $image_namecond=explode("-",$image);
                                  $image_namecond1=strtoupper($image_namecond[2])."-".$image_namecond[3]."-".@$image_namecond[4]."-".@$image_namecond[5];
                                  $image_namecond1=rtrim($image_namecond1,"-");
                                  $picture_name=mysqli_query($con,"select * from image_naming where order_id=$id_url and image_name='$image_namecond1'");
                                  }
                                  else{
                                    $picture_name=mysqli_query($con,"select * from image_naming where order_id=$id_url and image_name='$image'");
                                  }
                                  $picture_name1=mysqli_fetch_assoc($picture_name);

                                  // print_r($get_comment);
                                  ?>

                                   <input type="checkbox" class="selectimg"  name="selected_image[]" id="selected_image<?php echo $get_comment['id'];?>" value="<?php echo $get_comment['id'];?>" style="display:none;" />
                                   <input type="checkbox" class="selectall" name="allimage[]"  value="<?php echo $get_comment['id'];?> " checked  style="display:none;" >

                                  <div data-sort="1" class=" col-md-4 cat1" style="margin-right:-10px;margin-top: -50px;">

                                    <a class="img-box icons<?php echo $get_comment['id'];?>" id="imga" href="<?php echo $imagesDirectory_standard."/".$image; ?>" title="<?php echo $picture_name1['description']; ?>" style="visibility: hidden;" onmouseover="showicons(<?php echo $get_comment['id'];?>)">
                                        <i class="fa fa-eye" style="position:revert !important;top:50px;"></i>
                                    </a>

                                    <a class="icons<?php echo $get_comment['id'];?>" id="imga1" onclick="clickimg(<?php echo $get_comment['id'];?>)" style="visibility: hidden;" onmouseover="showicons(<?php echo $get_comment['id'];?>)">
                                        <i class="fa fa-square icons"  id="check<?php echo $get_comment['id'];?>" style="position:revert !important;top:50px;font-size: 16px;color:white !important;"></i>

                                    </a>
                                    <a  onclick="viewed(<?php echo $get_comment['id']?>)"  onmouseover="showicons(<?php echo $get_comment['id'];?>)"   onmouseout="hideicons(<?php echo $get_comment['id'];?>)">
                         <img alt="" class="img1 <?php if($get_comment['disapprove']==1){ echo "nonviewed"; }?>"  id="clicked_img<?php echo $get_comment['id'];?>"  title="<?php if($get_comment['disapprove']==1){ echo @$get_comment['comments']; }?>" src="<?php echo $imagesDirectory_standard."/".$image; ?>" height="240" width="240" style="z-index: -1;margin-bottom:5px;">
                                    </a>
                                      <div id="myModal<?php echo $get_comment['id'];?>" class="modal" style="">
                                        <!-- Modal content -->

                                        <div class="modal-content" style="height:260px;">
                                           <span class="close" onclick="document.getElementById('myModal<?php echo $get_comment['id'];?>').style='display:none'" style="margin: 10px;font-size: 25px;color: black;">&times;</span>

                                           <center> <img alt="" id="img" src="<?php echo $imagesDirectory_standard."/".$image; ?>" width="180" height="200" style="float:left;margin-left:40px;margin-right:40px" title="asfsadsdasds"/></center>
                                           <div style="float: left;margin-right: 0px;border-left:1px solid #DDD;">
                                             <?php
                                             $get_comment_querry=mysqli_query($con,"select * from img_upload where order_id=$id_url and img='$image'");
                                             $get_comment=mysqli_fetch_assoc($get_comment_querry);

                                             ?>
                                     <textarea id="s<?php echo $get_comment['id'];?>"  rows="4" cols="35" style="margin-left:20px;margin-top:30px"><?php echo $get_comment['comments'];?></textarea>
                                     <hr class="space s">
                                         <!--  -->
                                           </div>
                                        </div>

                                      </div>
                                    <?php /*  <a class="img-box " style="" href="<?php echo $imagesDirectory_standard."/".$image; ?>"   style="">
                                          <i class="fa fa-home "  style=""></i>

                                      </a> */ ?>

                                  </div>

                                  <?php

                                 }

                                }

                                  closedir($opendirectory);
                              }
                              ?>
                              <?php

                                   $raw_images_query=mysqli_query($con,"SELECT * FROM `raw_images` WHERE order_id=$id_url and service_name='1'");
                                   $get_link=mysqli_fetch_array($raw_images_query);

                              ?>

                                  <center><br /><input type="text" class="comment form-control" name="comment" id="comment2"  value="<?php echo @$get_link['comments'] ?>"placeholder="Enter the comment " style=""  required /></center>

                                 <input type="hidden" name="folderToZip" value="<?php echo "finished_images/order_".$id_url."/standard_photos"; ?>">
                                 <input type="hidden" name="Order_ID" id="getdata" value="<?php echo $id_url; ?>">
                                 <input type="hidden" name="service_ID" value="<?php echo '1'; ?>">
                               <hr class="space s">

                              <p align="right"><input type="submit" class="btn btn-default done" onclick="downloadbtn()" name="ZIP" value="Download" style="margin-right: 75%;">&nbsp;<a href="#tnc" class="btn btn-default lightbox link" onclick="shareme('<?php echo @$get_link['images_url']?>')" name="send2" id="send2" adr_trans="label_share">share</a></center></p>

                               </form>
                               <input type="number" id="counts" value="<?php echo $i;?>" style="display:none;"/>
                              </div>
                              </div>

                          </div>
                          <div class="panel fade-right" style="transition-duration: 300ms; animation-duration: 300ms; transition-timing-function: ease; transition-delay: 0ms;">
                            <div style="border-bottom: 1px solid black">

                                 <form onsubmit="return check2();" name="zipDownload" id="zipDownload2" method="post" action="">
                             <input type="checkbox" id="remove2" onclick="selectAllImages2()"><b adr_trans="label_select_all">Select All</b></input>
                               <button name="rework" onclick="reworks();" style="background-color: black;float:right;margin-right:20px;margin-top:-10px;border-radius: 12px;color: white;" adr_trans="label_rework">Rework</button>
                            </div>
                            <div class="maso-list gallery">
                              <div class="maso-box row no-margins" data-options="anima:fade-in" style="position: relative;">
                                 <input type="hidden" id="allimages2" name="allimages" value="0">
                              <?php
                              $imagesDirectory_floor = "./finished_images/order_".$id_url."/floor_plans";
                                $i=0;
                              if (is_dir($imagesDirectory_floor))
                              {
                               $opendirectory = opendir($imagesDirectory_floor);


                              while (($image = readdir($opendirectory)) !== false)
                               {
                                 if(($image == '.') || ($image == '..'))
                                 {
                                   continue;
                                 }
                                  $i++;
                                 $imgFileType = pathinfo($image,PATHINFO_EXTENSION);

                                 if(($imgFileType == 'jpg') || ($imgFileType == 'png'))
                                 {

                                  ?>

                                  <?php
                                //  echo "select * from img_upload where order_id=$id_url and img='$image'";
                                  $get_comment_querry=mysqli_query($con,"select * from img_upload where order_id=$id_url and img='$image'");
                                  $get_comment=mysqli_fetch_assoc($get_comment_querry);

                                  $checknaming=mysqli_query($con,"select * from image_naming where order_id=$id_url and image_name='$image'");
                                  $checknaming1=mysqli_fetch_assoc($checknaming);
                                  if($checknaming1['description']=="")
                                  {
                                  $image_namecond=explode("-",$image);
                                  $image_namecond1=strtoupper($image_namecond[2])."-".$image_namecond[3]."-".@$image_namecond[4]."-".@$image_namecond[5];
                                  $image_namecond1=rtrim($image_namecond1,"-");
                                  $picture_name=mysqli_query($con,"select * from image_naming where order_id=$id_url and image_name='$image_namecond1'");
                                  }
                                  else{
                                    $picture_name=mysqli_query($con,"select * from image_naming where order_id=$id_url and image_name='$image'");
                                  }
                                  $picture_name1=mysqli_fetch_assoc($picture_name);
                                  // print_r($get_comment);
                                  ?>
                                   <input type="checkbox" class="selectimg2"  name="selected_image[]" id="selected_image2<?php echo $get_comment['id'];?>" value="<?php echo $get_comment['id'];?>" style="display:none;" />
                                   <input type="checkbox" class="selectall" name="allimage[]" id="selectall2"value="<?php echo $get_comment['id'];?> " checked  style="display:none;" >

                                  <div data-sort="1" class=" col-md-4 cat1" style="margin-right:-10px;margin-top: -50px;">

                                    <a class="img-box icons<?php echo $get_comment['id'];?> " id="imga" href="<?php echo $imagesDirectory_floor."/".$image; ?>"   title="<?php echo $picture_name1['description']; ?>" style="visibility: hidden;" onmouseover="showicons(<?php echo $get_comment['id'];?>)">
                                        <i class="fa fa-eye " style="position:revert !important;top:50px;"></i>
                                    </a>
                                    <a class="icons<?php echo $get_comment['id'];?> " id="imga1" onclick="clickimg2(<?php echo $get_comment['id'];?>)" style="visibility: hidden;" onmouseover="showicons(<?php echo $get_comment['id'];?>)">
                                        <i class="fa fa-square icons2"  id="check2<?php echo $get_comment['id'];?>" style="position:revert !important;top:50px;font-size: 16px;color:white !important;"></i>

                                    </a>
                                      <a  onclick="viewed(<?php echo $get_comment['id']?>)"   onmouseover="showicons(<?php echo $get_comment['id'];?>)"   onmouseout="hideicons(<?php echo $get_comment['id'];?>)">
                            <img alt="" class="img12 <?php if($get_comment['disapprove']==1){ echo "nonviewed"; }?>" title="<?php if($get_comment['disapprove']==1){ echo @$get_comment['comments']; }?>" id="clicked_img2<?php echo $get_comment['id'];?>" src="<?php echo $imagesDirectory_floor."/".$image; ?>" height="240" width="240" style="z-index: -1;margin-bottom:5px;">
                          </a>


                                      <div id="myModal<?php echo $get_comment['id'];?>" class="modal" style="">
                                        <!-- Modal content -->

                                        <div class="modal-content" style="height:260px;">
                                           <span class="close" onclick="document.getElementById('myModal<?php echo $get_comment['id'];?>').style='display:none'" style="margin: 10px;font-size: 25px;color: black;">&times;</span>

                                           <center> <img alt="" id="img" src="<?php echo $imagesDirectory_floor."/".$image; ?>" width="180" height="200" style="float:left;margin-left:40px;margin-right:40px"/></center>
                                           <div style="float: left;margin-right: 0px;border-left:1px solid #DDD;">
                                             <?php
                                             $get_comment_querry=mysqli_query($con,"select * from img_upload where order_id=$id_url and img='$image'");
                                             $get_comment=mysqli_fetch_assoc($get_comment_querry);

                                             ?>
                                     <textarea id="s<?php echo $get_comment['id'];?>"  rows="4" cols="35" style="margin-left:20px;margin-top:30px"><?php echo $get_comment['comments'];?></textarea>
                                     <hr class="space s">
                                         <!--  -->
                                           </div>
                                        </div>

                                      </div>
                                      <a class="img-box " style="" href="<?php echo $imagesDirectory_floor."/".$image; ?>"   style="">
                                          <i class="fa fa-home "  style=""></i>

                                      </a>

                                  </div>

                                  <?php

                                 }

                                }

                                  closedir($opendirectory);
                              }
                              ?>
                              <?php

                                   $raw_images_query=mysqli_query($con,"SELECT * FROM `raw_images` WHERE order_id=$id_url and service_name='2'");
                                   $get_link=mysqli_fetch_array($raw_images_query);

                              ?>
                                  <center><br /><input type="text" class="comment form-control" name="comment" id="comment22"  value="<?php  echo @$get_link['comments']?>"placeholder="Enter the comment " style=""  required /></center>

                                 <input type="hidden" name="folderToZip" value="<?php echo "finished_images/order_".$id_url."/floor_plans"; ?>">

                                 <input type="hidden" name="service_ID" value="<?php echo '2'; ?>">
                               <hr class="space s">

                              <p align="right"><input type="submit" class="btn btn-default done" onclick="downloadbtn2()" name="ZIP"  value="Download " style="margin-right: 75%;">&nbsp;<a href="#tnc" class="btn btn-default lightbox link" onclick="shareme2('<?php echo @$get_link['images_url']?>')" name="send2" id="send2" adr_trans="label_share" >share</a></center></p>
                               </form>
                             <input type="number" id="counts2" value="<?php echo $i;?>" style="display:none;"/>
                              </div>
                              </div>
                          </div>
                          <div class="panel fade-right" style="transition-duration: 300ms; animation-duration: 300ms; transition-timing-function: ease; transition-delay: 0ms;">
                            <div style="border-bottom: 1px solid black">

                                 <form  onsubmit="return check3();" name="zipDownload" id="zipDownload3" method="post" action="">
                             <input type="checkbox" id="remove3" onclick="selectAllImages3()"><b adr_trans="label_select_all">Select All</b></input>
                               <button name="rework" onclick="reworks();" style="background-color: black;float:right;margin-right:20px;margin-top:-10px;border-radius: 12px;color: white;" adr_trans="label_rework">Rework</button>
                            </div>
                            <div class="maso-list gallery">
                              <div class="maso-box row no-margins" data-options="anima:fade-in" style="position: relative;">
                                 <input type="hidden" id="allimages3" name="allimages" value="0">
                              <?php
                              $imagesDirectory_Drone = "./finished_images/order_".$id_url."/Drone_photos";
                              $i=0;
                              if (is_dir($imagesDirectory_Drone))
                              {
                               $opendirectory = opendir($imagesDirectory_Drone);


                              while (($image = readdir($opendirectory)) !== false)
                               {
                                 if(($image == '.') || ($image == '..'))
                                 {
                                   continue;
                                 }
                                 $i++;
                                 $imgFileType = pathinfo($image,PATHINFO_EXTENSION);

                                 if(($imgFileType == 'jpg') || ($imgFileType == 'png'))
                                 {

                                  ?>

                                  <?php
                                //  echo "select * from img_upload where order_id=$id_url and img='$image'";
                                  $get_comment_querry=mysqli_query($con,"select * from img_upload where order_id=$id_url and img='$image'");
                                  $get_comment=mysqli_fetch_assoc($get_comment_querry);

                                  $checknaming=mysqli_query($con,"select * from image_naming where order_id=$id_url and image_name='$image'");
                                  $checknaming1=mysqli_fetch_assoc($checknaming);
                                  if($checknaming1['description']=="")
                                  {
                                  $image_namecond=explode("-",$image);
                                  $image_namecond1=strtoupper($image_namecond[2])."-".$image_namecond[3]."-".@$image_namecond[4]."-".@$image_namecond[5];
                                  $image_namecond1=rtrim($image_namecond1,"-");
                                  $picture_name=mysqli_query($con,"select * from image_naming where order_id=$id_url and image_name='$image_namecond1'");
                                  }
                                  else{
                                    $picture_name=mysqli_query($con,"select * from image_naming where order_id=$id_url and image_name='$image'");
                                  }
                                  $picture_name1=mysqli_fetch_assoc($picture_name);
                                  // print_r($get_comment);
                                  ?>
                                   <input type="checkbox" class="selectimg3"  name="selected_image[]" id="selected_image3<?php echo $get_comment['id'];?>" value="<?php echo $get_comment['id'];?>" style="display:none;" />
                                   <input type="checkbox" class="selectall" name="allimage[]" id="selectall3" value="<?php echo $get_comment['id'];?> " checked  style="display:none;" >

                                  <div data-sort="1" class=" col-md-4 cat1" style="margin-right:-10px;margin-top: -50px;">

                                    <a class="img-box icons<?php echo $get_comment['id'];?> " id="imga" href="<?php echo $imagesDirectory_Drone."/".$image; ?>" title="<?php echo $picture_name1['description']; ?>" style="visibility: hidden;" onmouseover="showicons(<?php echo $get_comment['id'];?>)">
                                        <i class="fa fa-eye " style="position:revert !important;top:50px;"></i>
                                    </a>
                                    <a class="icons<?php echo $get_comment['id'];?> " id="imga1" onclick="clickimg3(<?php echo $get_comment['id'];?>)" style="visibility: hidden;" onmouseover="showicons(<?php echo $get_comment['id'];?>)">
                                        <i class="fa fa-square icons3"  id="check3<?php echo $get_comment['id'];?>" style="position:revert !important;top:50px;font-size: 16px;color:white !important;"></i>

                                    </a>
                                      <a  onclick="viewed(<?php echo $get_comment['id']?>)" onmouseover="showicons(<?php echo $get_comment['id'];?>)"   onmouseout="hideicons(<?php echo $get_comment['id'];?>)">
                            <img alt="" class="img13 <?php if($get_comment['disapprove']==1){ echo "nonviewed"; }?>" title="<?php if($get_comment['disapprove']==1){ echo @$get_comment['comments']; }?>" id="clicked_img3<?php echo $get_comment['id'];?>" src="<?php echo $imagesDirectory_Drone."/".$image; ?>" height="240" width="240" style="z-index: -1;margin-bottom:5px;">
                          </a>


                                      <div id="myModal<?php echo $get_comment['id'];?>" class="modal" style="">
                                        <!-- Modal content -->

                                        <div class="modal-content" style="height:260px;">
                                           <span class="close" onclick="document.getElementById('myModal<?php echo $get_comment['id'];?>').style='display:none'" style="margin: 10px;font-size: 25px;color: black;">&times;</span>

                                           <center> <img alt="" id="img" src="<?php echo $imagesDirectory_Drone."/".$image; ?>" width="180" height="200" style="float:left;margin-left:40px;margin-right:40px"/></center>
                                           <div style="float: left;margin-right: 0px;border-left:1px solid #DDD;">
                                             <?php
                                             $get_comment_querry=mysqli_query($con,"select * from img_upload where order_id=$id_url and img='$image'");
                                             $get_comment=mysqli_fetch_assoc($get_comment_querry);

                                             ?>
                                     <textarea id="s<?php echo $get_comment['id'];?>"  rows="4" cols="35" style="margin-left:20px;margin-top:30px"><?php echo $get_comment['comments'];?></textarea>
                                     <hr class="space s">
                                         <!--  -->
                                           </div>
                                        </div>

                                      </div>
                                      <a class="img-box " style="" href="<?php echo $imagesDirectory_Drone."/".$image; ?>"   style="">
                                          <i class="fa fa-home "  style=""></i>

                                      </a>

                                  </div>

                                  <?php

                                 }

                                }

                                  closedir($opendirectory);
                              }
                              ?>
                              <?php

                                   $raw_images_query=mysqli_query($con,"SELECT * FROM `raw_images` WHERE order_id=$id_url and service_name='3'");
                                   $get_link=mysqli_fetch_array($raw_images_query);

                              ?>
                                  <center><br /><input type="text" class="comment form-control" name="comment" id="comment23"  value="<?php echo @$get_comment['comments']; ?>"placeholder="Enter the comment " style=""  required /></center>

                                 <input type="hidden" name="folderToZip" value="<?php echo "finished_images/order_".$id_url."/Drone_photos"; ?>">

                                 <input type="hidden" name="service_ID" value="<?php echo '3'; ?>">
                               <hr class="space s">

                              <p align="right"><input type="submit" class="btn btn-default done" onclick="downloadbtn3()" name="ZIP"  value="Download " style="margin-right: 75%;">&nbsp;<a href="#tnc" class="btn btn-default lightbox link" onclick="shareme3('<?php echo @$get_link['images_url']?>')" name="send2" id="send2"  adr_trans="label_share">share</a></center></p>
                               </form>
                               <input type="number" id="counts3" value="<?php echo $i;?>" style="display:none;"/>
                              </div>
                              </div>

                          </div>
                          <div class="panel fade-right" style="transition-duration: 300ms; animation-duration: 300ms; transition-timing-function: ease; transition-delay: 0ms;">
                            <div style="border-bottom: 1px solid black">

                                 <form  onsubmit="return check4();" name="zipDownload" id="zipDownload4" method="post" action="">
                               <input type="checkbox" id="remove4" onclick="selectAllImages4()"><b adr_trans="label_select_all">Select All</b></input>
                               <button name="rework" onclick="reworks();" style="background-color: black;float:right;margin-right:20px;margin-top:-10px;border-radius: 12px;color: white;" adr_trans="label_rework">Rework</button>
                            </div>
                            <div class="maso-list gallery">
                              <div class="maso-box row no-margins" data-options="anima:fade-in" style="position: relative;">
                                 <input type="hidden" id="allimages4" name="allimages" value="0">
                              <?php
                              $imagesDirectory_hdr = "./finished_images/order_".$id_url."/hdr_photos";
                               $i=0;
                              if (is_dir($imagesDirectory_hdr))
                              {
                               $opendirectory = opendir($imagesDirectory_hdr);


                              while (($image = readdir($opendirectory)) !== false)
                               {
                                 if(($image == '.') || ($image == '..'))
                                 {
                                   continue;
                                 }
                                  $i++;
                                 $imgFileType = pathinfo($image,PATHINFO_EXTENSION);

                                 if(($imgFileType == 'jpg') || ($imgFileType == 'png'))
                                 {

                                  ?>

                                  <?php
                                //  echo "select * from img_upload where order_id=$id_url and img='$image'";
                                  $get_comment_querry=mysqli_query($con,"select * from img_upload where order_id=$id_url and img='$image'");
                                  $get_comment=mysqli_fetch_assoc($get_comment_querry);

                                  $checknaming=mysqli_query($con,"select * from image_naming where order_id=$id_url and image_name='$image'");
                                  $checknaming1=mysqli_fetch_assoc($checknaming);
                                  if($checknaming1['description']=="")
                                  {
                                  $image_namecond=explode("-",$image);
                                  $image_namecond1=strtoupper($image_namecond[2])."-".$image_namecond[3]."-".@$image_namecond[4]."-".@$image_namecond[5];
                                  $image_namecond1=rtrim($image_namecond1,"-");
                                  $picture_name=mysqli_query($con,"select * from image_naming where order_id=$id_url and image_name='$image_namecond1'");
                                  }
                                  else{
                                    $picture_name=mysqli_query($con,"select * from image_naming where order_id=$id_url and image_name='$image'");
                                  }
                                  $picture_name1=mysqli_fetch_assoc($picture_name);
                                  // print_r($get_comment);
                                  ?>
                                   <input type="checkbox" class="selectimg4"  name="selected_image[]" id="selected_image4<?php echo $get_comment['id'];?>" value="<?php echo $get_comment['id'];?>" style="display:none;" />
                                   <input type="checkbox" class="selectall" name="allimage[]" id="selectal4" value="<?php echo $get_comment['id'];?> " checked  style="display:none;" >

                                  <div data-sort="1" class=" col-md-4 cat1" style="margin-right:-10px;margin-top: -50px;">

                                    <a class="img-box icons<?php echo $get_comment['id'];?>" id="imga" href="<?php echo $imagesDirectory_hdr."/".$image; ?>" title="<?php echo $picture_name1['description']; ?>" style="visibility: hidden;" onmouseover="showicons(<?php echo $get_comment['id'];?>)">
                                        <i class="fa fa-eye " style="position:revert !important;top:50px;"></i>
                                    </a>
                                    <a class="icons<?php echo $get_comment['id'];?>" id="imga1" onclick="clickimg4(<?php echo $get_comment['id'];?>)" style="visibility: hidden;" onmouseover="showicons(<?php echo $get_comment['id'];?>)">
                                        <i class="fa fa-square icons4"  id="check4<?php echo $get_comment['id'];?>" style="position:revert !important;top:50px;font-size: 16px;color:white !important;"></i>

                                    </a>
                                      <a  onclick="viewed(<?php echo $get_comment['id']?>)" onmouseover="showicons(<?php echo $get_comment['id'];?>)" onmouseout="hideicons(<?php echo $get_comment['id'];?>)">
                            <img alt="" class="img14 <?php if($get_comment['disapprove']==1){ echo "nonviewed"; }?>" title="<?php if($get_comment['disapprove']==1){ echo @$get_comment['comments']; }?>" id="clicked_img4<?php echo $get_comment['id'];?>" src="<?php echo $imagesDirectory_hdr."/".$image; ?>" height="240" width="240" style="z-index: -1;margin-bottom:5px;">
                                 </a>


                                      <div id="myModal<?php echo $get_comment['id'];?>" class="modal" style="">
                                        <!-- Modal content -->

                                        <div class="modal-content" style="height:260px;">
                                           <span class="close" onclick="document.getElementById('myModal<?php echo $get_comment['id'];?>').style='display:none'" style="margin: 10px;font-size: 25px;color: black;">&times;</span>

                                           <center> <img alt="" id="img" src="<?php echo $imagesDirectory_hdr."/".$image; ?>" width="180" height="200" style="float:left;margin-left:40px;margin-right:40px"/></center>
                                           <div style="float: left;margin-right: 0px;border-left:1px solid #DDD;">
                                             <?php
                                             $get_comment_querry=mysqli_query($con,"select * from img_upload where order_id=$id_url and img='$image'");
                                             $get_comment=mysqli_fetch_assoc($get_comment_querry);

                                             ?>
                                     <textarea id="s<?php echo $get_comment['id'];?>"  rows="4" cols="35" style="margin-left:20px;margin-top:30px"><?php echo $get_comment['comments'];?></textarea>
                                     <hr class="space s">
                                         <!--  -->
                                           </div>
                                        </div>

                                      </div>
                                      <a class="img-box " style="" href="<?php echo $imagesDirectory_hdr."/".$image; ?>"   style="">
                                          <i class="fa fa-home "  style=""></i>

                                      </a>

                                  </div>

                                  <?php

                                 }

                                }

                                  closedir($opendirectory);
                              }
                              ?>
                              <?php

                                   $raw_images_query=mysqli_query($con,"SELECT * FROM `raw_images` WHERE order_id=$id_url and service_name='4'");
                                   $get_link=mysqli_fetch_array($raw_images_query);

                              ?>
                                  <center><br /><input type="text" class="comment form-control" name="comment" id="comment24"  value="<?php echo @$get_link['comments'] ?>"placeholder="Enter the comment " style=""  required /></center>

                                 <input type="hidden" name="folderToZip" value="<?php echo "finished_images/order_".$id_url."/hdr_photos"; ?>">

                                 <input type="hidden" name="service_ID" value="<?php echo '4'; ?>">
                               <hr class="space s">

                              <p align="right"><input type="submit" class="btn btn-default done" onclick="downloadbtn4()" name="ZIP"  value="Download " style="margin-right: 75%;">&nbsp;<a href="#tnc" class="btn btn-default lightbox link" onclick="shareme4('<?php echo @$get_link['images_url']?>')" name="send2" id="send2"  adr_trans="label_share">share</a></center></p>
                               </form>
                                  <input type="number" id="counts4" value="<?php echo $i;?>" style="display:none;"/>
                              </div>
                              </div>

                          </div>
                      </div>


<br>
<br>
<!-- <?php

$get_order_query1=mysqli_query($con,"SELECT * FROM orders where id='$id_url'");
$get_order1=mysqli_fetch_array($get_order_query1);
if($get_order1['status_id']==3)
{
  echo '<script>$(".hiddens").hide();</script>';
}
?> -->

</div>
<div class="panel" id="tab4">
<form action="" method="GET" align="center">
<input class="search-field" id="search" type="text" placeholder="Type here" value="<?php echo $get_info['address']; ?>">
<input id="submit" type="submit" value="Search">
</form>

<hr class="space" />

</div> <link rel="stylesheet" href="./css/style_invoice.css">
<div class="panel" id="tab5">
  <div id="printtable"></div>
    <div id="print">
     
      <header id="inv_header" >
        <?php
        @$invoice_check_query=mysqli_query($con,"select * from invoice where order_id=$id_url");
        @$invoice_check=mysqli_fetch_assoc(@$invoice_check_query);?>

        <h1 id="inv_h1" style="font-size:50px; text-align: center;" adr_trans="label_order_cost">Order Cost</h1><p align="right"><a class="anima-button circle-button btn-sm btn adr-save" style="position: relative;margin-top: -100px;color:white !important;" id="noprint" onclick="printPage()"><i class="fa fa-print"></i><span adr_trans="label_print">Print</span></a></p>

        <hr class="space s">
         <table style="margin-left : 30px;width:100%">

            <tr>
              <th style="width:30%">
                <p style="font-size:14px" id="label_order_no" adr_trans="label_order_no"><strong>ORDER NO.</strong><br></p>
              </th>
			  <th style="width:40%;text-align:center" align="center">ORDER COST NO.</th>
              <th  style="width:30%" align="right">
                <p id="label_date_issue" adr_trans="label_date_issue" style="font-size:14px; margin-right:30px;float:right;
        "><strong> DATE OF ISSUE </strong><br></p>
              </th>
            </tr>
            <tr>
              <td style="width:30%" align="left">
                <p style="font-size:11px;text-align:left;"> <?php echo $id_url; ?></p>
              </td>
			   <td style="width:40%" align="center">
                <p style="font-size:11px;text-align:center;"> <?php echo "FOT".@$invoice_check['invoice_id']; ?></p>
              </td>
              <td style="width:30%" align="right">
                <p style="font-size:14px;float:right; margin-right:30px;"> <?php echo date("d/m/y"); echo " ("; echo date("h:i:a"); echo ")"; ?></p>
              </td>
            </tr>
          </table>
<table style="width:100%!important;margin-left : 30px;">
<tr><td style="width:70%!important;">
        <br />
          <?php
              $id_fetch=mysqli_query($con,"SELECT * FROM home_seller_info where id='$hs_id'");
              $get_id=mysqli_fetch_array($id_fetch);

              if ($get_id['lead_from'] == "realtor") {
              ?>
			 <table style="width:100%!important;">
              <tr><th align="left"><p style="font-size:14px"><strong adr_trans="label_billed_to"> BILLED TO </strong><br></p></th></tr>
              <tr>
                <th align="left"><p style="font-size:11px"><strong><?php  echo $get_id['request_name']; ?> </strong><br></p> </th> </tr>
                <tr><td><p style="font-size:11px"> <?php  echo $get_id['request_address']; ?></p></td></tr>
                <tr><td><p style="font-size:11px"> <?php   echo $get_id['request_email']; ?><br></p></td></tr>
           <tr><td><p style="font-size:11px"> <?php  echo $get_id['request_contact_no']; ?></p></td></tr>
		   </table>
              <?php
              }
              elseif ($get_id['lead_from'] == "homeseller") {
                ?>
				 <table style="width:100%!important;">
                <tr><th align="left"><p style="font-size:14px"><strong adr_trans="label_billed_to"> BILLED TO </strong><br></p></th></tr>
                <tr>
                  <th align="left"><p style="font-size:11px"><strong><?php  echo $get_id['name']; ?> </strong><br></p></th></tr>
                 <tr> <td><p style="font-size:11px"> <?php   echo $get_id['address']; ?><br></p></td></tr>
                  <tr><td><p style="font-size:11px"> <?php   echo $get_id['city']; echo " , "; echo $get_id['state']; ?><br></p></td></tr>
                  <tr><td><p style="font-size:11px"> <?php  echo "Zip Code : "; echo $get_id['zip']; ?><br></p></td></tr>
				  </table>
              <?php
              }
              else {
                 $created_Nam=$_SESSION["loggedin_id"];
                $get_created_name_query=mysqli_query($con,"SELECT * FROM user_login where id=".$created_Nam);
                $get_name_create=mysqli_fetch_assoc($get_created_name_query);
                ?>
				<table style="width:100%!important;">
                <tr><th align="left"><p style="font-size:14px"><strong adr_trans="label_billed_to"> BILLED TO </strong></p></th></tr>
                <tr>
                  <th align="left"><p style="font-size:11px"><strong><?php  echo $get_name_create["first_name"]." ".$get_name_create["last_name"]?> </strong><br></p></th></tr>
                  <tr><td><p style="font-size:11px"> <?php   echo $get_name_create['address_line1']; echo " , ";
                  echo $get_name_create['address_line2']; ?><br></p></td></tr>
                  <tr><td><p style="font-size:11px"> <?php   echo $get_name_create['city']; echo " , "; echo $get_name_create['state']; ?><br></p></td></tr>
                  <tr><td><p style="font-size:11px"> <?php  echo "Zip Code : "; echo $get_name_create['postal_code']; ?><br></p></td></tr>
                  </table>
                <?php
              }
           ?>
         
  

     </td>
	 <td style="width:50%">
          <table style="width:100%">
          
<br />
          <?php

    $get_order_query=mysqli_query($con,"SELECT * FROM orders where id='$id_url'");
    $get_order=mysqli_fetch_array($get_order_query);

    ?>

    <?php
              $pc_admin_id=$get_order['pc_admin_id'];
              $get_photo_info=mysqli_query($con,"SELECT * FROM photo_company_profile where pc_admin_id='$pc_admin_id'");
              $get_information=mysqli_fetch_assoc($get_photo_info);

              ?>
  <tr><th align="left"><p style="font-size:14px"><strong adr_trans="label_billed_from"> Billed From </strong><br></p></th></tr>
  <tr><th align="left"><p style="font-size:11px"><strong><?php  echo $get_information['organization_name']; ?> </strong><br></p></th></tr>
  <tr><td><p style="font-size:11px" > <?php   echo $get_information['address_line1']; echo " , "; echo $get_information['address_line2']; ?></p></td></tr>
  <tr><td><p style="font-size:11px" > <?php   echo $get_information['city']; echo " , "; echo $get_information['state']; ?><br></p></td></tr>
  <tr><td><p style="font-size:11px" > <?php  echo "Zip Code : "; echo $get_information['postal_code']; ?><br></p></td></tr>
      
       
        </table>
</td></tr></table>

<br /><br />

      </header>
      <article>


       
               
        <table id="inv_table1" class="inventory"  style="width:100%">
          <thead>
            <tr>
              <th id="inv_th" style="width:10% ;margin-left : 10px;
       padding-left : 10px;"><span adr_trans="label_product_desc"> PRODUCTS DESCRIPTION</span></th>
       <th id="inv_th" style="width:10% ;text-align: center;"><span>QUANTITY</span></th>
              <th id="inv_th" style="width:10% ;text-align: center;"><span adr_trans="label_costs">COSTS</span></th>
              <!-- <th id="inv_th" style="width:15%;text-align: center;"><span >OTHER COSTS</span></th>
              <th id="inv_th" style="width:15%;text-align: center;"><span >TOTAL COSTS</span></th> -->
            </tr>
          </thead>
          <tbody>
            <tr >
              <td id="inv_td" style="margin-left : 10px;

       padding-left : 10px;" ><span ><?php
        // echo "select group_concat(product_id) as product_id from order_products WHERE order_id='$id_url'";
       $prodsList=mysqli_query($con,"select group_concat(product_id) as product_id,group_concat(product_title) as product_title,group_concat(quantity) as quantity,sum(total_price)+sum(other_cost) as total from order_products WHERE order_id='$id_url'");
      $prodsList1=mysqli_fetch_array($prodsList);
      $product_id_is=$prodsList1['product_id'];
    //
    // echo "select GROUP_CONCAT(product_name) as title from products where id in ($product_id_is)";
                               // $product_query=mysqli_query($con,"select GROUP_CONCAT(product_name) as title from products where id in ($product_id_is)");
                               //  $product_detail=mysqli_fetch_array($product_query);
                                $title_split = @$prodsList1['product_title'];
                                // echo $prodsList1['product_title'];
                                $splited_title =  explode(',',$title_split);
                                foreach($splited_title as $new_title)
                                {
                                    echo $new_title; ?> <br/><?php
                                }?>

                                </span></td>

                                <td id="inv_td" style="text-align:center;"><span data-prefix></span><span><?php
                $quantity_split=$prodsList1['quantity'];
               $var=explode(',',$quantity_split);
               foreach($var as $row)
                {

               echo $row; ?> <br/><?php

                }

        ?></span></td>

            <td id="inv_td" style="text-align:center;"><span data-prefix></span><span><?php
              $product_id_split=$prodsList1['product_id'];
             $var=explode(',',$product_id_split);
             foreach($var as $row)
              {
               // echo "SELECT * FROM order_products where product_id='$row' and order_id='$id_url'";
              $price=mysqli_query($con,"SELECT * FROM order_products where product_id='$row' and order_id='$id_url'");
              $get_price_info=mysqli_fetch_assoc($price);
             $total_cost=@$get_price_info["total_price"];
             echo "$".@$total_cost; ?> <br/><?php

              }

      ?></span></td>

            </tr>
            <tr>
<td id="inv_th" colspan="1" style="text-align: right;"><span ></span></td>
            <td id="inv_th"  style="text-align: right;"><span adr_trans="label_other_cost" >Other cost</span><span><?php echo "(".$invoice_check['other_cost_comment'].")"?></span><span >:</span></td>
            <td id="inv_td" style="text-align: center;"><span data-prefix>$</span><span><?php echo $invoice_check['other_cost']; ?></span></td>
            </tr>
            <tr>
              <td id="inv_th" colspan="1" style="text-align: right;"><span ></span></td>
            <td id="inv_th"  style="text-align: right;"><span ><span adr_trans="label_tax">Tax</span>(<?php echo $get_information['tax']; ?>%)</span><span >:</span></td>
            <?php
            $percentage = $get_information['tax'];
            $totalcost = $prodsList1['total']+$invoice_check['other_cost'];
            $new_cost = ($percentage / 100) * $totalcost;
             ?>
            <td id="inv_td" style="text-align: center;"><span data-prefix>$</span><span><?php echo $new_cost; ?></span></td>
            </tr>

            <tr>
              <td id="inv_th" colspan="1" style="text-align: right;"><span ></span></td>
              <?php $final_value=$prodsList1['total']+$invoice_check['other_cost']+$new_cost?>
            <td id="inv_th"  style="text-align: right;"><span adr_trans="label_total">Total</span><span >:</span></td>
            <td id="inv_td" style="text-align: center;"><span data-prefix>$</span><span><?php echo $final_value; ?></span></td>
            </tr>
          <?php /*  <tr>
<td id="inv_th" colspan="1" style="text-align: right;"><span ></span></td>
      <td id="inv_th"  style="text-align: center;"><span adr_trans="label_total_price">Total Price</span></td>
      <td id="inv_td" style="text-align: center;"><span data-prefix>$</span><span><?php echo $final_value; ?></span></td>
    </tr> */ ?>
          </tbody>
        </table>


      </article>
      <br/><br/>
  <table style="margin-left : 10px;
       padding-left : 10px;">
    <tr>
      <th><p adr_trans="label_terms_condition">Terms and condtions </p></th>
    </tr>
    <td><p>E.g. Please pay Order Cost by MM/DD/YYYY</p></td>
  </table>

    </div>
    <script>

    function printPage()
    {
       var divToPrint=document.getElementById("print");
       newWin= window.open("");
       newWin.document.write(divToPrint.outerHTML);
       newWin.print();
       newWin.close();
    }
  </script>

</div>


</div>
  </div>

  <div id="tnc" class="box-lightbox white" style="padding:25px;border-radius:25px 25px 25px 25px;width:300px;height:200px;">
     <div class="subtitle g" style="color:#333333">
       <h5 style="color:#333333" align="center" adr_trans="label_enter_the_email">Enter the share Email</h5>
          <hr>
          <center><span class="sub" id="error" style="color:green;"></span></center>
          <form   method="post" name="stdform" action="" onsubmit="">
          <input id="email1" name="email" placeholder="Email" type="email" autocomplete="off"   class="form-control form-value" required>
          <input type="hidden" name="link1" id="link"/>
          <input type="hidden" name="sharename" value="<?php echo $loggedin_name;?>"  />
          <hr class="space s">
          <center><button class="btn adr-save" name="link" id="send" ><span adr_trans="label_send">Send</span></button></center>
          </form>
          <hr class="space l">




          </div>
                 </div>
<div class="col-md-2" style="border:none;background:#000;opacity:0.7;padding:10px;font-family:Verdana, Arial, Helvetica, sans-serif;border-radius:15px;">
  <p style="color:white;font-weight:600;padding-bottom:10px;" align="center">Chat with <b> <?php

  $realtor1=mysqli_query($con,"select * from user_login where id='$photographer_id'");
  $realtor=mysqli_fetch_array($realtor1);
    echo @$realtor["first_name"];  ?></p>
  <div id="wrapper" style="width:100%">
  <div class="scrollbar" id="style-default" style="border:none;background:#E8F0FE;overflow:scroll;width:100%">
  <table class="table" style="padding:5px;word-break:break-all; border:none;width:100%;" id="ChatBox" >

  </table>
</div>
</div>
  <input type="hidden" name="created_by_id" id="created_by_id" value="<?php echo $get_order["created_by_id"]; ?>" />
   <input type="hidden" name="order_id" id="order_id" value="<?php echo $get_order["id"]; ?>" />
   <input type="hidden" name="logged_id" id="logged_id" value="<?php echo $_SESSION["loggedin_id"]; ?>" />
  <input type="text" name="chattext" id="chattext1" style="border:solid 0px #000080;font-family:Verdana, Arial, Helvetica, sans-serif;font-size:11px;font-weight:600;border-radius:10px;" placeholder="Type your msg, hit enter" required class="form-control" />


  </div>

  <div id="aboutMe" class="box-lightbox white" style="padding:25px;height:336px;">
                  <div class="subtitle g" style="color:#333333">
                      <h5 style="color:#333333" align="center" id="label_photographer_details" adr_trans="label_photographer_details" >PHOTOGRAPHER DETAILS</h5>
                      <hr class="space s">

        <div class="tab-box right" data-tab-anima="fade-left">
                  <div class="panel-box col-md-8" id="resultDiv">
                    <form class="" action="#" method="post">


                   <input type="text" name="email" />
                   </form>
                  </div>


                  </ul>
              </div>

        </div>

</div>

<div id="tnc1" class="box-lightbox white" style="padding:25px;border-radius:25px 25px 25px 25px;width:300px;height:200px;">
   <div class="subtitle g" style="color:#333333">
     <h5 style="color:#333333" align="center" id="title"></h5>
        <hr>
        <center><span class="sub" id="error" style="color:green;"></span></center>

        <form   method="post" name="stdform" action="" onsubmit="">
        <input id="" name="reason" placeholder="Reason" type="text" autocomplete="off" class="form-control form-value" required>
        <input type="hidden" name="status_id" id="status_id"/>

        <hr class="space s">
        <center><button class="btn adr-save" name="link" id="send" ><span adr_trans="label_send">Send</span></button></center>
        </form>
        <hr class="space l">

        </div>
               </div>

  <script>

  $('#chattext1').keypress(function (e) {
 var key = e.which;
 if(key == 13)
  {
    var a=$("#created_by_id").val();
    var b=$("#order_id").val();
    var c=$("#logged_id").val();
    var d= $("#chattext1").val();
     $("#chattext1").val('');
    var xhttp = new XMLHttpRequest();
 xhttp.onreadystatechange = function() {
   if (this.readyState == 4 && this.status == 200) {
    //document.getElementById("demo").innerHTML = this.responseText;
   }

 };
 xhttp.open("GET","insert_chat.php?created_by_id="+a+"&logged_id="+c+"&chattext="+d+"&order_id="+b, true);
 xhttp.send();
 viewchat();

  }
});

function viewchat()
{
  var b=$("#order_id").val();
  var c=$("#logged_id").val();
  var xhttp = new XMLHttpRequest();
  xhttp.onreadystatechange = function() {
    if (this.readyState == 4 && this.status == 200) {
     document.getElementById("ChatBox").innerHTML = this.responseText;
    }
  };
  xhttp.open("GET","view_chat.php?id="+b+"&id1="+c, true);
  xhttp.send();
}

var scrolled = false;
function updateScroll(){
    if(!scrolled){
        var element = document.getElementById("style-default");
        element.scrollTop = element.scrollHeight;
    }
}

  </script>
    <script>

	var intervalId = window.setInterval(function(){
  viewchat();
  updateScroll();
}, 5000);
	</script>
  </div>
	</div>


 <?php if(@isset($_REQUEST["s"])) { ?>
 <script>$(document).ready(function() {
 $("#click1").addClass("active");
 $("#click2").removeClass("active");
 $("#tab1").addClass("active");
 $("#tab2").removeClass("active");
});
  </script>
  <?php } ?>

 <?php if(@isset($_REQUEST["a"])) { ?>
 <script>$(document).ready(function() {
 $("#click2").addClass("active");
 $("#click1").removeClass("active");
 $("#tab2").addClass("active");
 $("#tab1").removeClass("active");
});

$(document).ready(function(){
$("#selectall").click(function(){
        if(this.checked){
            $('.checkboxall').each(function(){
                $(".checkboxall").prop('checked', true);
            })
        }else{
            $('.checkboxall').each(function(){
                $(".checkboxall").prop('checked', false);
            })
        }
    });
});
  </script>
  <?php } ?>
		<?php include "footer.php";  ?>
