<?php
ob_start();
include "connection.php";
include "header.php";
$id_url=$_REQUEST['id'];

$get_order_query=mysqli_query($con,"select * from orders where id='$id_url'");
$get_order=mysqli_fetch_assoc($get_order_query);

function getName($n) {
    $characters = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";
    $randomString = '';

    for ($i = 0; $i < $n; $i++) {
        $index = rand(0, strlen($characters) - 1);
        $randomString .= $characters[$index];
    }

    return $randomString;
}
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;
function email($v,$x,$y,$z)
{
	/* Exception class. */
	require 'C:\PHPMailer\src\Exception.php';

	/* The main PHPMailer class. */
	require 'C:\PHPMailer\src\PHPMailer.php';

	/* SMTP class, needed if you want to use SMTP. */
	require 'C:\PHPMailer\src\SMTP.php';

	$mail = new PHPMailer(true);
	$mail->isSMTP();
	$mail->Host = 'smtp.gmail.com';
	$mail->SMTPAuth = true;
	//$mail->Username = 'sidambara.selvan@adrgrp.com'; //paste one generated by Mailtrap
	//$mail->Password = 'Selvan1#$'; //paste one generated by Mailtrap
	$mail->Username = 'test.deve@adrgrp.com';
	$mail->Password = 'adrgrp@123';
	$mail->SMTPSecure = 'tls';
	$mail->Port = 587;
	//$mail->Port = 465;
	//From email address and name
	$mail->From = "test.deve@adrgrp.com";
	$mail->FromName = "Fotopia";

	//To address and name
	// $mail->addAddress("ssselvan.83@gmail.com", "Selvan");
	// //$mail->addAddress("lakshminarayanan@adrgrp.com","Lakshmi"); //Recipient name is optional
	// //$mail->addAddress("srivatsan@adrgrp.com","Srivatsan");
	// $mail->addAddress("bharathwaj.v@adrgrp.com","Bharath");
	 $mail->addAddress($y);


	//Address to which recipient will reply
	$mail->addReplyTo("test.deve@adrgrp.com", "Reply");

	//CC and BCC
	//$mail->addCC("cc@example.com");
	//$mail->addBCC("bcc@example.com");

	//Send HTML or Plain Text email
	$mail->isHTML(true);

	$mail->Subject = "Image Upload successfully";
	$mail->Body = "<html><head><style>.titleCss {font-family: \"Roboto\",Helvetica,Arial,sans-serif;font-weight:600;font-size:18px;color:#0275D8 }.emailCss { width:100%;border:solid 1px #DDD;font-family: \"Roboto\",Helvetica,Arial,sans-serif; } </style></head><table cellpadding=\"5\" class=\"emailCss\"><tr><td align=\"left\"><img src=\"http://fotopia.adrgrp.com/logo.png\" /></td><td align=\"center\" class=\"titleCss\">RAW IMAGE UPLOAD SUCCESSFUL</td><td align=\"right\">info@fotopia.com<br>343 4543 213</td></tr><tr><td colspan=\"2\"><br><br>";
	//$mail->AltBody = "This is the plain text version of the email content";
	$mail->Body.="Hello {{Editor_email}},<br>

You have been assigned for Photo edit work from {{Photographer_Name}} through
Fotopia with the order reference # F{{orderId}}.<br>
<a href='{{project_url}}/download_raw_images.php?secret_code={{secret_code}}'
target='_blank'>Click here</a> to view and download the images.<br><br>
You can upload the Finished images in the same link above.
<br><br>
Thanks,<br>
Fotopia Team.
";
  $mail->Body=str_replace('{{secret_code}}', $v , $mail->Body);
	$mail->Body=str_replace('{{project_url}}', $_SESSION['project_url'] , $mail->Body);
  $mail->Body=str_replace('{{Photographer_Name}}', $x , $mail->Body);
	$mail->Body=str_replace('F{{orderId}}',$z, $mail->Body);
  	$mail->Body=str_replace('{{Editor_email}}',$y, $mail->Body);
	$mail->Body.="<br><br></td></tr></table></html>";
	//echo $mail->Body;exit;
	try {
	    $mail->send();
	    echo "Message has been sent successfully";
	} catch (Exception $e) {
		echo $e->getMessage();
	    echo "Mailer Error: " . $mail->ErrorInfo;
	}
}

  $stdPicCount=0;
  $floorPicCount=0;
  $dronePicCount=0;
  $hdrpicCount=0;
if(isset($_POST['email']))
{
  $secret_code=getName(16);
  $editor_email=$_REQUEST["email"];

  $split=explode("/",$_SERVER["HTTP_REFERER"]);
  $url=$split[0]."//".$split[2]."/".$split[3]."/download_raw_images.php?secret_code=".$secret_code;
  $SESSION=$_SESSION["loggedin_id"];
  $comment=$_REQUEST['commentall'];
  $filecount = count(glob("./raw_images/order_$id_url/standard_photos/" . "*"));
  $query="INSERT INTO `raw_images`(`images_url`, `security_code`, `order_id`, `editor_email`, `sent_by`, `sent_on`, `status`,`service_name`,`comments`,`total_files`) VALUES ('$url','$secret_code',$id_url,'$editor_email',$SESSION,now(),1,1,'$comment','$filecount')";
  $insert=mysqli_query($con,$query);
  $photographer_id=$SESSION;
  $get_photgrapher_name_query=mysqli_query($con,"SELECT * FROM user_login where id='$photographer_id'");
  $get_name=mysqli_fetch_assoc($get_photgrapher_name_query);
  $photographer_Name=$get_name["first_name"]."".$get_name["last_name"];
  email($secret_code,$photographer_Name,$editor_email,$id_url);
  header("location:photographerorder_detail.php?id=".$id_url);

 }
if(isset($_POST['floor_email']))
{
  $secret_code=getName(16);
  $editor_email=$_REQUEST["floor_email"];

  $split=explode("/",$_SERVER["HTTP_REFERER"]);
  $url=$split[0]."//".$split[2]."/".$split[3]."/download_raw_images.php?secret_code=".$secret_code;
  $SESSION=$_SESSION["loggedin_id"];
  $photographer_id=$SESSION;
  $get_photgrapher_name_query=mysqli_query($con,"SELECT * FROM user_login where id='$photographer_id'");
  $get_name=mysqli_fetch_assoc($get_photgrapher_name_query);
  $photographer_Name=$get_name["first_name"]."".$get_name["last_name"];


  $filecount = count(glob("./raw_images/order_$id_url/floor_plans/" . "*"));

  $query="INSERT INTO `raw_images`(`images_url`, `security_code`, `order_id`, `editor_email`, `sent_by`, `sent_on`, `status`,`service_name`,`total_files`) VALUES ('$url','$secret_code',$id_url,'$editor_email',$SESSION,now(),1,2,'$filecount')";
  $insert=mysqli_query($con,$query);
  email($secret_code,$photographer_Name,$editor_email,$id_url);
  header("location:photographerorder_detail.php?id=".$id_url);

  }
if(isset($_POST['Drone_email']))
{
  $secret_code=getName(16);
  $editor_email=$_REQUEST["Drone_email"];

  $split=explode("/",$_SERVER["HTTP_REFERER"]);
  $url=$split[0]."//".$split[2]."/".$split[3]."/download_raw_images.php?secret_code=".$secret_code;
  $SESSION=$_SESSION["loggedin_id"];
  $photographer_id=$SESSION;
  $get_photgrapher_name_query=mysqli_query($con,"SELECT * FROM user_login where id='$photographer_id'");
  $get_name=mysqli_fetch_assoc($get_photgrapher_name_query);
  $photographer_Name=$get_name["first_name"]."".$get_name["last_name"];
  $filecount = count(glob("./raw_images/order_$id_url/Drone_photos/" . "*"));
  $query="INSERT INTO `raw_images`(`images_url`, `security_code`, `order_id`, `editor_email`, `sent_by`, `sent_on`, `status`,`service_name`,`total_files`) VALUES ('$url','$secret_code',$id_url,'$editor_email',$SESSION,now(),1,3,'$filecount')";
  $insert=mysqli_query($con,$query);
  email($secret_code,$photographer_Name,$editor_email,$id_url);




  header("location:photographerorder_detail.php?id=".$id_url);

 }
 if(isset($_POST['hdr_email']))
 {
   $secret_code=getName(16);
   $editor_email=$_REQUEST["hdr_email"];

   $split=explode("/",$_SERVER["HTTP_REFERER"]);
   $url=$split[0]."//".$split[2]."/".$split[3]."/download_raw_images.php?secret_code=".$secret_code;
   $SESSION=$_SESSION["loggedin_id"];
   $photographer_id=$SESSION;
   $get_photgrapher_name_query=mysqli_query($con,"SELECT * FROM user_login where id='$photographer_id'");
   $get_name=mysqli_fetch_assoc($get_photgrapher_name_query);
   $photographer_Name=$get_name["first_name"]."".$get_name["last_name"];
    $filecount = count(glob("./raw_images/order_$id_url/Hdr_photos/" . "*"));
   $query="INSERT INTO `raw_images`(`images_url`, `security_code`, `order_id`, `editor_email`, `sent_by`, `sent_on`, `status`,`service_name`,`total_files`) VALUES ('$url','$secret_code',$id_url,'$editor_email',$SESSION,now(),1,4,'$filecount')";
   $insert=mysqli_query($con,$query);
   email($secret_code,$photographer_Name,$editor_email,$id_url);
   header("location:photographerorder_detail.php?id=".$id_url);

   }
?>
<style>
.active
{
  background: none !important;
}


</style>
<script>
function show_editbtn(d)
{

  var c=$("#editor_email1").val();

  if(c!=='')
  {
    $("#edit_button").show();
    $("#email1").val(c);

  }

  else {
    $("#edit_button").hide();

  }
}
function show_editbtn2()
{
  var c=$("#editor_email2").val();

  if(c!=='')
  {
    $("#edit_button1").show();
      $("#email2").val(c);
  }
  else {
    $("#edit_button1").hide();
  }
}
function show_editbtn3()
{
  var c=$("#editor_email3").val();

  if(c!=='')
  {
    $("#edit_button2").show();
      $("#email3").val(c);

  }
  else {
    $("#edit_button2").hide();
  }
}
function show_editbtn4()
{
  var c=$("#editor_email4").val();

  if(c!=='')
  {
    $("#edit_button3").show();
      $("#email4").val(c);
  }
  else {
    $("#edit_button3").hide();
  }
}
</script>

<script>
var a;
                    function confirmEmail(a)
					{
                       // var a='Please confirm this is the right email - '+$("#email"+a).val();
                       if(1)
                       {
                       return true;
                       }
                       else
                       {
                        return false;
                        }
                   }


                   </script>


 <div class="section-empty bgimage3">
        <div class="container" style="margin-left:0px;height:inherit">
            <div class="row">
			<hr class="space s">
                <div class="col-md-2">
<?php include "sidebar.php"; ?>
			          </div>
                <div class="col-md-10" style="background:#000;color:#FFF;opacity:0.9">
                <hr class="space s">


                  <h5 style="border-bottom:solid 2px #a94442;border-left:solid 12px #a94442;padding:10px" adr_trans="label_standard_photos">Standard Photos</h5>

                   <button href="" class="btn btn-primary"  id="edit_button" data-lightbox-anima="show-scale" style="display:block;float:right;margin-top: -50px;" adr_trans="label_send"> Send</button>
                   <select name="editor_email" id="editor_email1" onchange="show_editbtn(this.val)" style="display:none;float:right;margin-top: -47px;color: black;margin-right: 74px;height: 32px;min-width: 110px;">

                    <?php
                      $photographer_id=$_SESSION['loggedin_id'];
                      $pc_admin_id=$get_order['pc_admin_id'];
                     $editor_query=mysqli_query($con,"SELECT * FROM `editor` WHERE photographer_id='$photographer_id' ");

                     while($editor=mysqli_fetch_array($editor_query))
                     {
                       ?>

                       <option value="<?php echo $editor['email'] ?>"> <?php echo $editor['organization_name'] ?></option>
                       <?php
                     }
                    ?>
                   </select>
                  <div class="maso-list gallery">
                    <div class="maso-box row no-margins" data-options="anima:fade-in" style="position: relative;">
                    <?php
                    $imagesDirectory_standard = "./raw_images/order_".$id_url."/standard_photos";

                    if (is_dir($imagesDirectory_standard))
                    {
                     $opendirectory = opendir($imagesDirectory_standard);
                     while (($image = readdir($opendirectory)) !== false)
                     {
                       if(($image == '.') || ($image == '..'))
                       {
                         continue;
                       }
                       $imgFileType = pathinfo($image,PATHINFO_EXTENSION);
                       if(($imgFileType == 'jpg') || ($imgFileType == 'png'))
                       {
                        ?>
                        <div data-sort="1" class=" col-md-2 cat1" style="visibility: visible; height:fit-content; padding:20px;">
                            <a class="img-box i-center" href="<?php echo $imagesDirectory_standard."/".$image; ?>" data-anima="show-scale" data-trigger="hover" data-anima-out="hide" style="opacity: 1;">
                                <i class="fa fa-photo anima" aid="0.22880302434786803" style="transition-duration: 500ms; animation-duration: 500ms; transition-timing-function: ease; transition-delay: 0ms; opacity: 0;"></i>
                                <img alt="" id="img" src="<?php echo $imagesDirectory_standard."/".$image; ?>"   height="80"/>
                            </a>
                            <?php
                          //  echo "SELECT * FROM `image_naming` WHERE order_id=$id_url and image_name='$image'";
                            $get_comment_querry=mysqli_query($con,"SELECT * FROM `image_naming` WHERE order_id=$id_url and image_name='$image'");
                            $get_comment=mysqli_fetch_assoc($get_comment_querry);

							$stdPicCount=mysqli_num_rows($get_comment_querry);
                            ?>
                            <center>
                              <input type="text" list="pic_type" class="form-control stdImg" size="" id="myBtn<?php echo $get_comment['id']; ?>" value="<?php echo $get_comment['description']; ?>" style="width:120px;margin-top:10px;" onchange="myFunction(event,<?php echo  $get_comment['id'];?>)" required placeholder="Name the pic"/>
                              <datalist id="pic_type" />
                                <option value="">choose your description</option>
                              <?php
                                $description_query=mysqli_query($con,"SELECT * FROM `image_interior_exterior_name` ");
                                while($description=mysqli_fetch_array($description_query))
                                {
                                  ?>
                                  <option value="<?php echo $description['name'];?>" <?php if($get_comment['description']== $description['name']) {echo "selected";}?> ><?php echo $description['name'];?></option>
                          <?php  }?>
                        </datalist>
                          </center>

                        </div>
                        <script>
                        function myFunction(e,data)
                         {
                        var key = e.which;
                          if(1)
                          {
                            var a=$("#myBtn"+data).val();
                            var xhttp = new XMLHttpRequest();
                          xhttp.onreadystatechange = function() {
                           if (this.readyState == 4 && this.status == 200) {
                             if(this.responseText=="true")
                             {
                              // alert("description Uploaded");
                             }
                           }
                          };
                          xhttp.open("GET","description.php?id="+data+"&id1="+a+"&type=standard_photos&user=photographer", true);
                          xhttp.send();
                          }
                        }
                        </script>


                        <?php
                       }

                     }

                        closedir($opendirectory);
                    }
                    ?>
                    </div>
                    <br><center><input type="text" name="commentall" id="comment_all1" placeholder="Comment here"  onkeyup="show_editbtn(this.form)" style="width:90%;color: black;"/><center>
                    </div>
                    <hr class="space l">
                    <h5 style="border-bottom:solid 2px #4caf50;border-left:solid 12px #4caf50;padding:10px">Floor Plans</h5>
                       <button href="" class="btn btn-primary"  id="edit_button1" data-lightbox-anima="show-scale" style="display:block;float:right;margin-top:-50px" adr_trans="label_send"> Send</button>
                        <select name="editor_email" id="editor_email2"  onchange="show_editbtn2()" style="display:none;float:right;margin-top: -47px;color: black;margin-right: 74px;height: 32px;min-width: 110px;">
                          <?php
                            $photographer_id=$_SESSION['loggedin_id'];
                            $pc_admin_id=$get_order['pc_admin_id'];
                           $editor_query=mysqli_query($con,"SELECT * FROM `editor` WHERE photographer_id='$photographer_id'");
                           while($editor=mysqli_fetch_array($editor_query))
                           {
                             ?>

                             <option value="<?php echo $editor['email'] ?>"> <?php echo $editor['organization_name'] ?></option>
                             <?php
                           }
                          ?>
                         </select>
                    <hr>
                    <div class="maso-list gallery">
                      <div class="maso-box row no-margins" data-options="anima:fade-in" style="position: relative;">
                      <?php
                      $imagesDirectory_floor = "./raw_images/order_".$id_url."/floor_plans";

                      if (is_dir($imagesDirectory_floor))
                      {
                       $opendirectory = opendir($imagesDirectory_floor);


                          while (($image = readdir($opendirectory)) !== false)
                       {
                         if(($image == '.') || ($image == '..'))
                         {
                           continue;
                         }

                         $imgFileType = pathinfo($image,PATHINFO_EXTENSION);

                         if(($imgFileType == 'jpg') || ($imgFileType == 'png'))
                         {
                          ?>
                          <div data-sort="1" class=" col-md-2 cat1" style="visibility: visible; height:fit-content; padding:20px;">
                              <a class="img-box i-center" href="<?php echo $imagesDirectory_floor."/".$image; ?>" data-anima="show-scale" data-trigger="hover" data-anima-out="hide" style="opacity: 1;">
                                  <i class="fa fa-photo anima" aid="0.22880302434786803" style="transition-duration: 500ms; animation-duration: 500ms; transition-timing-function: ease; transition-delay: 0ms; opacity: 0;"></i>

                                  <img alt="" id="img" src="<?php echo $imagesDirectory_floor."/".$image; ?>" width="100" height="80"/>
                              </a>
                              <?php
                              $get_comment_querry=mysqli_query($con,"SELECT * FROM `image_naming` WHERE order_id=$id_url and image_name='$image'");
                              $get_comment=mysqli_fetch_assoc($get_comment_querry);
							 $floorPicCount=mysqli_num_rows($get_comment_querry);
                              ?>
                              <input type="text" list="pic_type1"class="form-control stdImg1"  id="myBtn<?php echo $get_comment['id']; ?>" value="<?php echo $get_comment['description']; ?>" style="width:120px;margin-top:10px;" onchange="myFunction1(event,<?php echo  $get_comment['id'];?>)" required placeholder="Name the pic"/>
                              <datalist id="pic_type1" />

                   <option value="">choose your description</option>
                 <?php
                   $description_query=mysqli_query($con,"SELECT * FROM `image_interior_exterior_name` ");
                   while($description=mysqli_fetch_array($description_query))
                   {
                     ?>
                     <option value="<?php echo $description['name']; ?>" <?php if($get_comment['description']== $description['name']) {echo "selected";}?> ><?php echo $description['name'];?></option>
             <?php  }?>
           </datalist>

                          </div>
                          <script>
                          function myFunction1(e,data)
                           {
                          var key = e.which;
                            if(1)
                            {
                              var a=$("#myBtn"+data).val();
                              var xhttp = new XMLHttpRequest();
                            xhttp.onreadystatechange = function() {
                             if (this.readyState == 4 && this.status == 200) {
                               if(this.responseText=="true")
                               {
                                 //alert("description Uploaded");
                               }
                             }
                            };
                            xhttp.open("GET","description.php?id="+data+"&id1="+a+"&type=floor_plans&user=photographer", true);
                            xhttp.send();
                            }
                          }
                          </script>
                          <?php
                         }
                        }
                          closedir($opendirectory);
                        }
                      ?>
                      </div>
                        <br><center><input type="text" name="commentall" id="comment_all2" placeholder="Comment here"  onkeyup="show_editbtn2(this.form)" style="width:90%;color: black;"/><center>
                      </div>
                      <hr class="space l">
                    <h5 style="border-bottom:solid 2px #357d8f;border-left:solid 12px #357d8f;padding:10px">Drone Photos</h5>
                           <button  class="btn btn-primary"  id="edit_button2" data-lightbox-anima="show-scale" style="display:block;float:right;margin-top:-50px" adr_trans="label_send">Send</button>

                            <select name="editor_email" onchange="show_editbtn3()" id="editor_email3" style="display: none;float:right;margin-top: -47px;color: black;margin-right: 74px;height: 32px;min-width: 110px;">

                              <?php
                                $photographer_id=$_SESSION['loggedin_id'];
                                $pc_admin_id=$get_order['pc_admin_id'];
                               $editor_query=mysqli_query($con,"SELECT * FROM `editor` WHERE photographer_id='$photographer_id'");
                               while($editor=mysqli_fetch_array($editor_query))
                               {
                                 ?>

                                 <option value="<?php echo $editor['email'] ?>"> <?php echo $editor['organization_name'] ?></option>
                                 <?php
                               }
                              ?>
                             </select>
                    <hr>
                    <div class="maso-list gallery">
                      <div class="maso-box row no-margins" data-options="anima:fade-in" style="position: relative;">
                      <?php
                      $imagesDirectory_Drone = "./raw_images/order_".$id_url."/Drone_photos";
                      if (is_dir($imagesDirectory_Drone))
                      {
                       $opendirectory = opendir($imagesDirectory_Drone);
                          while (($image = readdir($opendirectory)) !== false)
                       {
                         if(($image == '.') || ($image == '..'))
                         {
                           continue;
                         }
                         $imgFileType = pathinfo($image,PATHINFO_EXTENSION);
                         if(($imgFileType == 'jpg') || ($imgFileType == 'png'))
                         {
                          ?>
                          <div data-sort="1" class=" col-md-2 cat1" style="visibility: visible; height:fit-content; padding:20px;">
                              <a class="img-box i-center" href="<?php echo $imagesDirectory_Drone."/".$image; ?>" data-anima="show-scale" data-trigger="hover" data-anima-out="hide" style="opacity: 1;">
                                  <i class="fa fa-photo anima" aid="0.22880302434786803" style="transition-duration: 500ms; animation-duration: 500ms; transition-timing-function: ease; transition-delay: 0ms; opacity: 0;"></i>
                                  <img alt="" id="img" src="<?php echo $imagesDirectory_Drone."/".$image; ?>" width="100" height="80"/>
                              </a>
                              <?php
                              $get_comment_querry=mysqli_query($con,"SELECT * FROM `image_naming` WHERE order_id=$id_url and image_name='$image'");
                              $get_comment=mysqli_fetch_assoc($get_comment_querry);

							  $dronePicCount=mysqli_num_rows($get_comment_querry);
                              ?>
                              <input type="text" list="pic_type2" class="form-control stdImg2"  id="myBtn<?php echo $get_comment['id']; ?>" value="<?php echo $get_comment['description']; ?>" style="width:120px;margin-top:10px;" onchange="myFunction2(event,<?php echo  $get_comment['id'];?>)" required placeholder="Name the pic"/>
                              <datalist id="pic_type2" />

                   <option value="">choose your description</option>
                 <?php
                   $description_query=mysqli_query($con,"SELECT * FROM `image_interior_exterior_name` ");
                   while($description=mysqli_fetch_array($description_query))
                   {
                     ?>
                     <option value="<?php echo $description['name'];?>" <?php if($get_comment['description']== $description['name']) {echo "selected";}?>><?php echo $description['name'];?></option>
             <?php  }?>
           </datalist>

                          </div>
                          <script>
                          function myFunction2(e,data)
                           {
                          var key = e.which;
                            if(1)
                            {
                              var a=$("#myBtn"+data).val();
                              var xhttp = new XMLHttpRequest();
                            xhttp.onreadystatechange = function() {
                             if (this.readyState == 4 && this.status == 200) {

                             }
                            };
                            xhttp.open("GET","description.php?id="+data+"&id1="+a+"&type=Drone_photos&user=photographer", true);
                            xhttp.send();
                            }
                          }
                          </script>
                          <?php
                         }
                        }
                        closedir($opendirectory);
                    }
                    ?>
                      </div>
                        <br><center><input type="text" name="commentall" id="comment_all3" placeholder="Comment here"  onkeyup="show_editbtn3(this.form)" style="width:90%;color: black;"/><center>
                      </div>

                      <hr class="space l">
                    <h5 style="border-bottom:solid 2px #357d8f;border-left:solid 12px #357d8f;padding:10px">HDR Photos</h5>
                           <button href=""  class="btn btn-primary" id="edit_button3" data-lightbox-anima="show-scale" style="display:block;float:right;margin-top:-50px" adr_trans="label_send"> Send</button>
                            <select name="editor_email" id="editor_email4" onchange="show_editbtn4()" style="display: none;float:right;margin-top: -47px;color: black;margin-right: 74px;height: 32px;min-width: 110px;">

                              <?php
                                $photographer_id=$_SESSION['loggedin_id'];
                                $pc_admin_id=$get_order['pc_admin_id'];
                               $editor_query=mysqli_query($con,"SELECT * FROM `editor` WHERE photographer_id='$photographer_id' ");
                               while($editor=mysqli_fetch_array($editor_query))
                               {
                                 ?>

                                 <option value="<?php echo $editor['email'] ?>"> <?php echo $editor['organization_name'] ?></option>
                                 <?php
                               }
                              ?>
                             </select>
                    <hr>
                    <div class="maso-list gallery">
                      <div class="maso-box row no-margins" data-options="anima:fade-in" style="position: relative;">
                      <?php
                      $imagesDirectory_Hdr = "./raw_images/order_".$id_url."/HDR_photos";
                      if (is_dir($imagesDirectory_Hdr))
                      {
                       $opendirectory = opendir($imagesDirectory_Hdr);
                          while (($image = readdir($opendirectory)) !== false)
                       {
                         if(($image == '.') || ($image == '..'))
                         {
                           continue;
                         }
                         $imgFileType = pathinfo($image,PATHINFO_EXTENSION);
                         if(($imgFileType == 'jpg') || ($imgFileType == 'png'))
                         {
                          ?>
                          <div data-sort="1" class=" col-md-2 cat1" style="visibility: visible; height:fit-content; padding:20px;">
                              <a class="img-box i-center" href="<?php echo $imagesDirectory_Hdr."/".$image; ?>" data-anima="show-scale" data-trigger="hover" data-anima-out="hide" style="opacity: 1;">
                                  <i class="fa fa-photo anima" aid="0.22880302434786803" style="transition-duration: 500ms; animation-duration: 500ms; transition-timing-function: ease; transition-delay: 0ms; opacity: 0;"></i>
                                  <img alt="" id="img" src="<?php echo $imagesDirectory_Hdr."/".$image; ?>" width="100" height="80"/>
                              </a>
                              <?php
                              $get_comment_querry=mysqli_query($con,"SELECT * FROM `image_naming` WHERE order_id=$id_url and image_name='$image'");
                              $get_comment=mysqli_fetch_assoc($get_comment_querry);

                $hdrpicCount=mysqli_num_rows($get_comment_querry);
                              ?>
                              <input type="text" list="pic_type3" class="form-control stdImg3"  id="myBtn<?php echo $get_comment['id']; ?>" value="<?php echo $get_comment['description']; ?>" style="width:120px;margin-top:10px;" onchange="myFunction3(event,<?php echo  $get_comment['id'];?>)" required placeholder="Name the pic"/>
                              <datalist id="pic_type3" />


                     <option value="">choose your description</option>
                   <?php
                     $description_query=mysqli_query($con,"SELECT * FROM `image_interior_exterior_name` ");
                     while($description=mysqli_fetch_array($description_query))
                     {
                       ?>
                       <option value="<?php echo $description['name'];?>" <?php if($get_comment['description']== $description['name']) {echo "selected";}?>><?php echo $description['name'];?></option>
               <?php  }?>
             </datalist>

                          </div>
                          <script>
                          function myFunction3(e,data)
                           {
                          var key = e.which;
                            if(1)
                            {
                              var a=$("#myBtn"+data).val();
                              var xhttp = new XMLHttpRequest();
                            xhttp.onreadystatechange = function() {
                             if (this.readyState == 4 && this.status == 200) {

                             }
                            };
                            xhttp.open("GET","description.php?id="+data+"&id1="+a+"&type=HDR_photos&user=photographer", true);
                            xhttp.send();
                            }
                          }
                          </script>
                          <?php
                         }
                        }
                        closedir($opendirectory);
                    }
                    ?>
                      </div>
                        <br><center><input type="text" name="commentall" id="comment_all4" placeholder="Comment here"  onkeyup="show_editbtn4(this.form)" style="width:90%;color: black;"/><center>
                      </div>
                    <br>
                    <br>
                </div>
              </div>
          </div>
          <div id="tnc" class="box-lightbox white" style="display:block;padding:25px;border-radius:25px 25px 25px 25px;width:300px;height:200px;">
             <div class="subtitle g" style="color:#333333">
               <h5 style="color:#333333" align="center">Enter the Editor Email</h5>
                  <hr>
                  <center>  <span class="sub" id="error" style="color:green;"></span> </center>

                  <form   method="post" name="stdform" id="standard_form" action="" onsubmit="return confirmEmail(1)">
                  <input id="email1" name="email" placeholder="Email" type="email" autocomplete="off" class="form-control form-value" required>
                  <hr class="space s">
                   <input type="hidden" name="commentall" id="cmt1"/>
                  <center><button class="btn adr-save" id="send" >Send</button></center>
                  </form>
                  <hr class="space l">




                  </div>
                         </div>


                         <div id="floor" class="box-lightbox white" style="padding:25px;border-radius:25px 25px 25px 25px;width:300px;height:200px;">
                            <div class="subtitle g" style="color:#333333">
                              <h5 style="color:#333333" align="center">Enter the editor Email</h5>
                                 <hr>
                                 <center>  <span class="sub" id="error" style="color:green;"></span> </center>

                                 <form   method="post" name="floorform" id="floor_form" action="" onsubmit="return confirmEmail(2)">
                                 <input id="email2" name="floor_email" placeholder="Email" type="email" autocomplete="off" class="form-control form-value" required>
                                 <hr class="space s">
                                  <input type="hidden" name="commentall" id="cmt2"/>
                                 <center><button class="btn adr-save" id="send1" >Send</button></center>
                                 </form>
                                 <hr class="space l">




                                </div>
                                        </div>
                                        <div id="Drone" class="box-lightbox white"  style="padding:25px;border-radius:25px 25px 25px 25px;width:300px;height:200px;">
                                           <div class="subtitle g" style="color:#333333">
                                             <h5 style="color:#333333" align="center">Enter the Editor Email</h5>
                                                <hr>
                                                <center>  <span class="sub" id="error" style="color:green;"></span> </center>
                                                <form  method="post" name="droneform" id="drone_form" action="" onsubmit="return confirmEmail(3)">
                                                <input id="email3" name="Drone_email" placeholder="Email" type="email" autocomplete="off" class="form-control form-value" required>
                                                <hr class="space s">
                                                 <input type="hidden" name="commentall" id="cmt3"/>
                                                <center><button class="btn adr-save" id="send2" >Send</button></center>
                                                </form>
                                                <hr class="space l">

                                                </div>
                                                 </div>

                                                 <div id="hdr" class="box-lightbox white"  style="padding:25px;border-radius:25px 25px 25px 25px;width:300px;height:200px;">
                                                    <div class="subtitle g" style="color:#333333">
                                                      <h5 style="color:#333333" align="center">Enter the Editor Email</h5>
                                                         <hr>
                                                         <center>  <span class="sub" id="error" style="color:green;"></span> </center>
                                                         <form  method="post" name="" id="hdr_form" action="" onsubmit="return confirmEmail(4)">
                                                         <input id="email4" name="hdr_email" placeholder="Email" type="email" autocomplete="off" class="form-control form-value" required>
                                                         <input type="hidden" name="commentall" id="cmt4"/>
                                                         <hr class="space s">
                                                         <center><button class="btn adr-save" id="send3" >Send</button></center>
                                                         </form>
                                                         <hr class="space l">

                                                         </div>
                                                          </div>

                                                          <?php $get_rawimages_query=mysqli_query($con,"SELECT * FROM `raw_images` WHERE order_id=$id_url");
                                                            while($get_images=mysqli_fetch_assoc($get_rawimages_query))
                                                            {
                                                                if($get_images["service_name"] == 1)
                                                                {
                                                                  echo '<script>$("#editor_email1").hide();$("#comment_all1").hide();$("#edit_button").hide();</script>';
                                                                }
                                                                if( $get_images["service_name"] == 2)
                                                                {
                                                                  echo '<script>$("#editor_email2").hide();$("#comment_all2").hide();$("#edit_button2").hide();</script>';
                                                                }
                                                                if($get_images["service_name"] == 3)
                                                                {
                                                                  echo '<script>$("#editor_email3").hide();$("#comment_all3").hide();$("#edit_button3").hide();</script>';
                                                                }
                                                                if($get_images["service_name"] == 4)
                                                                {
                                                                  echo '<script>$("#editor_email4").hide();$("#comment_all4").hide();$("#edit_button4").hide();</script>';
                                                                }

                                                            }
                                                            ?>


				<script>

        $('#edit_button').on('click', function (event) {
        $(".stdImg").each(function(){

            if($.trim($(this).val()) === '') {

                 alert('Please fill the naming for each image in Standard Photos.');
        		exit(0);
        		return false;

            } else {
                $(this).css("border","none");

        	return true;
                //console.log('Everything has a value.');
            }
        	});
          var c=$("#comment_all1").val();
          if(c=='')
          {
           
			var langIs='<?php echo $_SESSION['Selected_Language_Session']; ?>';
		var alertmsg='';
		if(langIs=='no')
		{
		alertmsg="Vennligst skriv inn standardkommentarer";
		}
		else
		{
		alertmsg="Please enter the Standard Comments";
		}
alert(alertmsg);
          }
          else {
            var d=$("#comment_all1").val();
            $("#cmt1").val(d);

             $("#standard_form").submit();
          }
        });



        $('.stdImg').on('keypress', function (event) {
          var keyCode = (event.keyCode ? event.keyCode : event.which);
      if (keyCode == 13) {
        $(".stdImg").each(function(){

            if($.trim($(this).val()) === '') {
              $(this).css("border","solid 5px red");
              $(this).focus();
                // alert('Please fill the naming for each image in Standard Photos.');
            exit(0);
            return false;

            } else {
                  $(this).css("border","none");

          return true;
                //console.log('Everything has a value.');
            }
          });
        }});
        $('.stdImg1').on('keypress', function (event) {
          var keyCode = (event.keyCode ? event.keyCode : event.which);
      if (keyCode == 13) {
        $(".stdImg1").each(function(){

            if($.trim($(this).val()) === '') {
              $(this).css("border","solid 5px red");
              $(this).focus();
                // alert('Please fill the naming for each image in Standard Photos.');
            exit(0);
            return false;

            } else {
                  $(this).css("border","none");

          return true;
                //console.log('Everything has a value.');
            }
          });
        }});
        $('.stdImg2').on('keypress', function (event) {
          var keyCode = (event.keyCode ? event.keyCode : event.which);
      if (keyCode == 13) {
        $(".stdImg2").each(function(){

            if($.trim($(this).val()) === '') {
              $(this).css("border","solid 5px red");
              $(this).focus();
                // alert('Please fill the naming for each image in Standard Photos.');
            exit(0);
            return false;

            } else {
                  $(this).css("border","none");

          return true;
                //console.log('Everything has a value.');
            }
          });
        }});
        $('.stdImg3').on('keypress', function (event) {
          var keyCode = (event.keyCode ? event.keyCode : event.which);
      if (keyCode == 13) {
        $(".stdImg3").each(function(){

            if($.trim($(this).val()) === '') {
            
                alert('Please fill the naming for each image in Standard Photos.');
            exit(0);
            return false;

            } else {
                  $(this).css("border","none");

          return true;
                //console.log('Everything has a value.');
            }
          });
        }});




        $('#edit_button1').on('click', function (event) {
        $(".stdImg1").each(function(){
            if($.trim($(this).val()) === '') {
                alert('Please fill the naming for each image in Floor plan Photos.');
        		exit(0);
        		return false;
            } else {
        	return true;
                //console.log('Everything has a value.');
            }
        	});
          var c=$("#comment_all2").val();
          if(c=='')
          {
            
			var langIs='<?php echo $_SESSION['Selected_Language_Session']; ?>';
		var alertmsg='';
		if(langIs=='no')
		{
		alertmsg="Vennligst skriv inn kommentarene til gulvet";
		}
		else
		{
		alertmsg="Please enter the Floor Comments";
		}
alert(alertmsg);
          }
          else {
              var d=$("#comment_all2").val();
              $("#cmt2").val(d);
              $("#floor_form").submit();
          }
        });
        $('#edit_button2').on('click', function (event) {
        $(".stdImg2").each(function(){

            if($.trim($(this).val()) === '') {
                alert('Please fill the naming for each image in Drone Photos.');
        		exit(0);
        		return false;

            } else {

        	return true;
                //console.log('Everything has a value.');
            }
        	});
          var c=$("#comment_all3").val();
          if(c=='')
          {
            var langIs='<?php echo $_SESSION['Selected_Language_Session']; ?>';
		var alertmsg='';
		if(langIs=='no')
		{
		alertmsg="Vennligst skriv drone kommentarer";
		}
		else
		{
		alertmsg="Please enter the Drone Comments";
		}
alert(alertmsg);
          }
          else {
            var d=$("#comment_all3").val();
            $("#cmt3").val(d);
            $("#drone_form").submit();
          }
        });
        $('#edit_button3').on('click', function (event) {
        $(".stdImg3").each(function(){

            if($.trim($(this).val()) === '') {
                alert('Please fill the naming for each image in Hdr Photos.');
        		exit(0);
        		return false;

            } else {
        	return true;
                //console.log('Everything has a value.');
            }
        	});
          var c=$("#comment_all4").val();
          if(c=='')
          {
            var langIs='<?php echo $_SESSION['Selected_Language_Session']; ?>';
		var alertmsg='';
		if(langIs=='no')
		{
		alertmsg="Vennligst skriv HDR kommentarer";
		}
		else
		{
		alertmsg="Please enter the HDR Comments";
		}
alert(alertmsg);
          }
          else {
            var d=$("#comment_all4").val();
            $("#cmt4").val(d);
            $("#hdr_form").submit();
          }
        });
        </script>
<?php if(@$stdPicCount==0)
{?>
<script>
// $("#edit_button").hide();
$("#editor_email1").hide();
$("#comment_all1").hide();
$("#edit_button").hide();
</script>
<?php } ?>

<?php
echo $floorPicCount;

if(@$floorPicCount==0)
{?>
<script>
// $("#edit_button1").hide();
$("#editor_email2").hide();
$("#comment_all2").hide();
$("#edit_button1").hide();
</script>
<?php } ?>
<?php if(@$dronePicCount==0)
{?>
<script>
//$("#edit_button").hide();
$("#editor_email3").hide();
$("#comment_all3").hide();
$("#edit_button2").hide();
</script>

<?php } ?>
<?php if(@$hdrpicCount==0)
{?>
<script>
// $("#edit_button3").hide();
$("#editor_email4").hide();
$("#comment_all4").hide();
$("#edit_button3").hide();
</script>

<?php } ?>





	<?php include "footer.php";  ?>
